#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

const die = m => { console.error(`ERREUR: ${m}`); process.exit(1); };
const norm = s => String(s).replaceAll('\\','/').replace(/^\.\//,'');
function root(){ let d=process.cwd(); while(!fs.existsSync(path.join(d,'.agent','MANIFEST.json'))){const p=path.dirname(d);if(p===d)throw Error('.agent introuvable');d=p;}return d; }
function json(f){return JSON.parse(fs.readFileSync(f,'utf8').replace(/^\uFEFF/,''));}
function put(f,v){fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n','utf8');}
function run(r,args,opt={}){return spawnSync(args[0],args.slice(1),{cwd:r,encoding:'utf8',shell:false,stdio:opt.inherit?'inherit':['ignore','pipe','pipe']});}
function ok(x,label){if(x.status!==0)throw Error(`${label}: ${(x.stderr||x.stdout||'').trim()}`);return (x.stdout||'').trim();}
const git=(r,...a)=>run(r,['git',...a]);
const branch=r=>ok(git(r,'branch','--show-current'),'git branch');
const head=r=>ok(git(r,'rev-parse','HEAD'),'git rev-parse');
function args(){const [cmd='help',...a]=process.argv.slice(2),o={};for(let i=0;i<a.length;i++)if(a[i].startsWith('--')){const k=a[i].slice(2),n=a[i+1];if(n&&!n.startsWith('--')){o[k]=n;i++;}else o[k]=true;}return{cmd,o};}
function req(o,k){if(!o[k]||o[k]===true)throw Error(`Option obligatoire: --${k}`);return String(o[k]);}
function paths(r,id){return{task:path.join(r,'.agent','tasks',id+'.md'),state:path.join(r,'.agent','state',id+'.json'),worklog:path.join(r,'.agent','worklogs',id+'.md'),handoff:path.join(r,'.agent','handoffs',id+'.md'),evidence:path.join(r,'.agent','evidence',id),arbitration:path.join(r,'.agent','arbitrations',id+'.md')};}
function states(r){return fs.readdirSync(path.join(r,'.agent','state')).filter(x=>/^T-\d{3}\.json$/.test(x)).map(x=>json(path.join(r,'.agent','state',x))).sort((a,b)=>a.task_id.localeCompare(b.task_id));}
function depsDone(r,s){return(s.depends_on||[]).every(id=>json(paths(r,id).state).status==='DONE');}
function nextReady(r){const m=json(path.join(r,'.agent','MANIFEST.json')),all=states(r),p=all.find(s=>s.task_id===m.next_ready_task);return p?.status==='READY'&&depsDone(r,p)?p:all.find(s=>s.status==='READY'&&depsDone(r,s));}
function dirty(r){const raw=run(r,['git','status','--porcelain=v1','-uall']);if(raw.status!==0)throw Error(`git status: ${(raw.stderr||raw.stdout||'').trim()}`);const out=(raw.stdout||'').replace(/\r?\n$/,'');if(!out)return[];return out.split(/\r?\n/).map(l=>norm(l.slice(3).trim()));}
function audit(r,action,s,actor,details=''){const f=path.join(r,'.agent','audit.ndjson');fs.appendFileSync(f,JSON.stringify({at:new Date().toISOString(),action,task:s.task_id,agent:actor,branch:s.branch,details})+'\n');}
function dash(r){const l=['# STATUS — Chantier PDP','','> Généré par `scripts/agent.mjs`.','', '| ID | Statut | Agent | Branche | Prochaine action |','|---|---|---|---|---|'];for(const s of states(r))l.push(`| ${s.task_id} | ${s.status} | ${s.agent||'—'} | ${s.branch||'—'} | ${(s.next_action||'—').replaceAll('|','/')} |`);fs.writeFileSync(path.join(r,'.agent','STATUS.md'),l.join('\n')+'\n');}
function log(r,s,event,msg,next=s.next_action){const p=paths(r,s.task_id);fs.mkdirSync(path.dirname(p.worklog),{recursive:true});if(!fs.existsSync(p.worklog))fs.writeFileSync(p.worklog,`# WORKLOG — ${s.task_id}\n\n- Tâche : ${s.title}\n- Branche : ${s.branch}\n\n`);fs.appendFileSync(p.worklog,`## ${new Date().toISOString()} — ${event}\n\n- Résultat : ${String(msg).replace(/\r?\n/g,' ')}\n- Commit : ${head(r)}\n- Prochaine action : ${next||'—'}\n\n`);}
function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');}
function sources(r,id){const f=path.join(r,'.agent','SOURCES.json');if(!fs.existsSync(f))return;for(const s of(json(f).sources||[]).filter(x=>!(x.required_for||[]).length||x.required_for.includes(id))){const p=path.join(r,norm(s.path));if(!fs.existsSync(p))throw Error(`Source absente: ${s.path}`);if(s.sha256&&sha(p)!==s.sha256.toLowerCase())throw Error(`Checksum source invalide: ${s.path}`);}}
function active(r){const b=branch(r),a=states(r).filter(s=>s.branch===b&&['IN_PROGRESS','AWAITING_DECISION','BLOCKED','REVIEW'].includes(s.status));if(a.length!==1)throw Error(`Tâche active introuvable sur ${b}`);return a[0];}
function push(r,s,msg){const files=dirty(r);for(const f of files)ok(git(r,'add','-A','--',f),`git add ${f}`);if(git(r,'diff','--cached','--quiet').status!==0)ok(git(r,'commit','-m',msg),'git commit');ok(git(r,'push','-u','origin',s.branch),'git push');return head(r);}
function start(r,o){const agent=req(o,'agent'),m=json(path.join(r,'.agent','MANIFEST.json')),s=o.task?json(paths(r,o.task).state):nextReady(r);if(!s)throw Error('Aucune tâche READY');if(s.status!=='READY'||!depsDone(r,s))throw Error('Tâche non exécutable');if(dirty(r).length)throw Error('Working tree non propre');ok(git(r,'ls-remote','origin','HEAD'),'Accès GitHub');ok(git(r,'fetch','origin','--prune'),'git fetch');sources(r,s.task_id);const b=`agent/${s.task_id.toLowerCase()}`;if(git(r,'ls-remote','--exit-code','--heads','origin',b).status===0)throw Error(`${b} existe déjà: utiliser resume`);ok(git(r,'switch','-C',b,`origin/${m.base_branch||'main'}`),'git switch');s.status='IN_PROGRESS';s.agent=agent;s.branch=b;s.started_at=new Date().toISOString();s.base_commit=head(r);s.next_action='Exécuter une petite unité puis save.';put(paths(r,s.task_id).state,s);log(r,s,'START','Accès écriture validé et branche créée.');audit(r,'STARTED',s,agent);dash(r);const c=push(r,s,`chore(${s.task_id.toLowerCase()}): start by ${agent}`);console.log(`TASK=${s.task_id}\nBRANCH=${b}\nPUSH=${c}`);}
function save(r,o){const s=active(r);if(s.status!=='IN_PROGRESS')throw Error('Tâche non IN_PROGRESS');const msg=req(o,'message');s.next_action=o['next-action']||'Continuer.';s.last_checkpoint_at=new Date().toISOString();put(paths(r,s.task_id).state,s);log(r,s,'CHECKPOINT',msg);audit(r,'CHECKPOINT',s,s.agent,msg);dash(r);console.log(`PUSH=${push(r,s,`wip(${s.task_id.toLowerCase()}): ${msg}`)}`);}
function gate(r,c){const x=spawnSync(c,{cwd:r,shell:true,encoding:'utf8',maxBuffer:50*1024*1024});return{command:c,result:x.status===0?'PASS':'FAIL',exit_code:x.status,output:`${x.stdout||''}${x.stderr||''}`.trim()};}
function pr(r,s){if(run(r,['gh','--version']).status!==0||run(r,['gh','auth','status']).status!==0)return null;const v=run(r,['gh','pr','view',s.branch,'--json','url','--jq','.url']);if(v.status===0&&v.stdout.trim())return v.stdout.trim();const x=run(r,['gh','pr','create','--draft','--base','main','--head',s.branch,'--title',`${s.task_id} — ${s.title}`,'--body',s.summary||s.title]);return x.status===0?x.stdout.trim():null;}
function finish(r,o){const s=active(r),summary=req(o,'summary');if(s.status!=='IN_PROGRESS')throw Error('Tâche non IN_PROGRESS');const results=(s.gates||[]).map(c=>gate(r,c)),failed=results.some(x=>x.result==='FAIL'),p=paths(r,s.task_id);s.status=failed?'BLOCKED':'REVIEW';s.finished_at=new Date().toISOString();s.summary=summary;s.gate_results=results;s.blocking_reason=failed?'Gate en échec':null;s.next_action=failed?'Corriger les gates.':'Revue humaine et merge.';fs.mkdirSync(p.evidence,{recursive:true});put(path.join(p.evidence,'agent-gates.json'),results);fs.writeFileSync(p.handoff,`# HANDOFF — ${s.task_id}\n\n- Statut : ${s.status}\n- Branche : ${s.branch}\n- Résumé : ${summary}\n- Prochaine action : ${s.next_action}\n`);put(p.state,s);log(r,s,'FINISH',summary);audit(r,'FINISHED',s,s.agent,s.status);dash(r);const c=push(r,s,`${failed?'wip':'feat'}(${s.task_id.toLowerCase()}): ${s.title}`),url=pr(r,s);console.log(`Tâche: ${s.task_id}\nStatut: ${s.status}\nBranche: ${s.branch}\nDernier commit: ${c}\nPR: ${url||'non créée'}\nGates: ${results.map(x=>x.result).join('/')||'Aucun'}\nRésumé: ${summary}`);}
function block(r,o){const s=active(r),reason=req(o,'reason'),next=req(o,'next-action');s.status='BLOCKED';s.blocking_reason=reason;s.next_action=next;put(paths(r,s.task_id).state,s);log(r,s,'BLOCKED',reason,next);audit(r,'BLOCKED',s,s.agent,reason);dash(r);console.log(`PUSH=${push(r,s,`wip(${s.task_id.toLowerCase()}): blocked`)}`);}
function resume(r,o){const id=req(o,'task'),agent=req(o,'agent'),b=`agent/${id.toLowerCase()}`;ok(git(r,'fetch','origin','--prune'),'git fetch');ok(git(r,'switch','-C',b,`origin/${b}`),'git switch');ok(git(r,'pull','--ff-only','origin',b),'git pull');const s=json(paths(r,id).state);if(!['IN_PROGRESS','BLOCKED'].includes(s.status))throw Error('Tâche non reprenable');s.status='IN_PROGRESS';s.agent=agent;s.resumed_at=new Date().toISOString();put(paths(r,id).state,s);log(r,s,'RESUME','Reprise depuis GitHub.');audit(r,'RESUMED',s,agent);dash(r);console.log(`PUSH=${push(r,s,`chore(${id.toLowerCase()}): resume by ${agent}`)}`);}
function arbitrate(r,o){const s=active(r),q=req(o,'question'),opts=req(o,'options').split('|').map(x=>x.trim()).filter(Boolean),rec=req(o,'recommendation'),ctx=req(o,'context'),next=req(o,'next-action');if(opts.length<2||opts.length>3)throw Error('2 ou 3 options requises');s.status='AWAITING_DECISION';s.arbitration={question:q,options:opts,recommendation:rec,context:ctx,requested_at:new Date().toISOString()};s.next_action=`Après décision: ${next}`;const p=paths(r,s.task_id);fs.mkdirSync(path.dirname(p.arbitration),{recursive:true});fs.writeFileSync(p.arbitration,`# ARBITRAGE — ${s.task_id}\n\n## Décision attendue\n${q}\n\n## Faits\n${ctx}\n\n## Options\n${opts.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n## Recommandation\n${rec}\n\n## Décision\n_En attente._\n`);put(p.state,s);log(r,s,'ARBITRATION',q,s.next_action);audit(r,'ARBITRATION_REQUIRED',s,s.agent,q);dash(r);const c=push(r,s,`chore(${s.task_id.toLowerCase()}): request arbitration`);console.log(`Tâche: ${s.task_id}\nStatut: AWAITING_DECISION\nBranche: ${s.branch}\nDernier commit: ${c}\nPR: ${pr(r,s)||'non créée'}\nDécision attendue: ${q}\nOptions: ${opts.join(' | ')}\nRecommandation: ${rec}`);}
function doctor(r){const m=json(path.join(r,'.agent','MANIFEST.json'));ok(git(r,'rev-parse','--is-inside-work-tree'),'Git');ok(git(r,'ls-remote','origin','HEAD'),'Origin');sources(r);console.log(`Gouvernance: ${m.governance_version}\nRuntime: ${m.runtime}\nMode: ${m.execution_mode}\nDiagnostic: PASS`);}
function status(r){dash(r);console.log(fs.readFileSync(path.join(r,'.agent','STATUS.md'),'utf8'));}
function help(){console.log('node scripts/agent.mjs start|save|finish|block|resume|arbitrate|doctor|status');}
try{const r=root(),{cmd,o}=args();({start,save,finish,block,resume,arbitrate,doctor,status}[cmd]||help)(r,o);}catch(e){die(e.message||String(e));}
