/**
 * @feature       catalog
 * @type          feature
 * @domain        catalog
 * @status        production
 * @owner         backend-core
 * @since         2025-09
 * @doctrine      docs/doctrine/FEATURE_DOCTRINE.md
 * @registry      docs/doctrine/APP_FEATURE_REGISTRY.md
 */
'use strict';

module.exports = {
  name:     'catalog',
  nature:   'feature',   // feature | capability | governance-unit
  type:     'feature',
  domain:   'catalog',
  status:   'production',
  owner:    'backend-core',

  classification: {
    axis:     'business',
    kind:     'business-feature',
    rationale: [
      'Propriétaire exclusif de products, catalog_media, product_variants, product_skus, product_sku_media, et des règles de canonicalisation, dédoublonnage et publication (arbitrage D, 2026-07-29).',
      "possède le contrat produit public, le lifecycle de publication et la vérité SKU/media ; pricing, routing et ranking restent consommés depuis leurs features propriétaires",
    ],
  },
  since:    '2025-09',
  doctrine: 'docs/doctrine/FEATURE_DOCTRINE.md',

  service: 'Raffiner les donnees fournisseur en catalogue canonique, publier les unites vendables et exposer un contrat detail produit stable a la Boutique.',

  perimeter: {
    in: [
      'connecteurs fournisseurs (CSV, API, manuel, Noon, CJdropshipping, AliExpress, Allegro Sandbox, eBay Sandbox Browse enregistré dans le dispatch générique P3)',
      'contrat source fournisseur versionne V1/V2 : brut integral + preservation explicite media, axes et unites vendables quand la source les connait',
      'publication produit et déclenchement de l audit prix via economic-engine',
      'categories boutique admin',
      'catalogue vivant Boutique : grille, cartes produit, ouverture fiche produit',
      'catalogue canonique : produit, medias publics, axes d options descriptifs et unites vendables SKU',
      'contrat detail produit public v1 : identity, pricing, media, option_axes, sellable_units et delivery_options deja resolues par leurs autorites',
      'projection des rails de livraison deja commercialement exposes par logistics, sans inventer prix ni delai',
      'modal produit catalogue : un fetch Product Detail, un etat de selection SKU, deux compositions responsive mobile/desktop',
      'raffinerie catalogue : donnee source EN conservee, eligibilite douane/transport (catalog_exclusions), enrichissement FR, overrides traces, approbation humaine unique',
      'contrat de revue du texte incruste dans les medias fournisseur : preuve attachee a la source et variante, traduction FR revue sans dependance IA specifique (verification pure, sans publication automatique)',
      'projection live Sources -> Raffinerie -> Boutique dans le Workspace Catalogue : observation des sources, du pipeline et du buyer-effective sans reprendre l autorite de mutation Sourcing ni de pricing marche',
      'glossaire metier EN->FR (catalog_glossary)',
      'mémoire terminologique externe sourcée et filtrée par corpus (catalog_terminology_reference), avec priorité au glossaire Komerce',
      'challenge FR cold-start permanent : 100 produits CJ jamais vus, source exacte, enrichissement TERMIUM incrémental, aucune dépendance IA runtime et seconde revue obligatoire',
      'campagne FR Quality branchée : traductions + reviews hashées → dry-run → application atomique en overrides manuels sur drafts inactifs → readiness → checkpoint, jamais de publication automatique',
      'gate final Raffinerie→Catalogue : 974 candidats attendus, vérité source V2, médias, SKU/SOI complets, catégorie, file humaine, zéro exposition marché avant publication ; mode final exige en plus contenu FR revu + publication guard PASS',
      'file d approbation admin (etage 6) : approve/reject/override en un ecran, seul point de validation humaine avant lifecycle_status=active',
      'bootstrap visuel CJ borné : 63 produits réels, médias fournisseur liés au lignage, exécution one-shot gardée',
      'pool CJ de Raffinerie borné à 1000 références propres maximum, dédupliqué et reprenable, sans publication automatique',
      'source Allegro Sandbox vendeur : offres exactes V2 en PLN, OAuth refresh chiffré sous verrou, aucun achat automatique',
      'source AliExpress de stress-test Raffinerie : Open Platform Drop Shipping api-sg, OAuth serveur géré et chiffré, feed/detail normalisés V2, aucune publication automatique',
      'pool AliExpress staging borné à 500 références réellement en stock, dédupliqué et reprenable, alimenté exclusivement via la Raffinerie et sans publication automatique',
      'product_market_exposure : exposition commerciale produit x marché, fail-closed (absence de ligne = DISABLED), même patron que commercial_exposure sur physical_offers/services',
      'migration 206 : snapshot de compatibilité produit x marché, reproduction exacte de publicCatalogVisibilitySql() croisée avec chaque marché actif — cutover, pas un all x all aveugle',
      'services/catalog-public-view.js::publicCatalogVisibilitySql(alias, { marketCodeParam }) : le chemin de lecture storefront consulte désormais product_market_exposure quand un marché est fourni ; sans marché, comportement historique inchangé à l’identique',
    ],
    out: [
      'calcul du prix final et valorisation transport (feature economic-engine)',
      'decision de rail, routing et eligibilite logistique dynamique (feature logistics)',
      'mise en avant / classement (feature recommendations)',
      'fiche snapshot lecture seule du panier partage (feature shared-cart)',
      'checkout final et paiement (features orders/payments)',
      'décision d’exposition produit x marché (qui écrit product_market_exposure) : feature market-delegation, capability catalog.expose',
    ],
  },

  files: {
    middleware: [
      'middleware/require-catalog-global-authority.js',
    ],
    ci: [
      '.github/workflows/showcase-v2-staging-deploy.yml',
      '.github/workflows/cj-real-showcase-contract.yml',
      '.github/workflows-disabled/showcase-catalog-media-audit.yml',
      '.github/workflows-disabled/showcase-catalog-staging-deploy.yml',
      '.github/workflows-disabled/README-CJ-SHOWCASE.md',
      // Rattachées (audit gouvernance 2026-09) — workflows ops staging
      // déjà revus et gardés (KEEP) lors de l'audit CI initial, jamais
      // déclarés dans aucun manifest feature jusqu'ici.
      '.github/workflows/staging-aliexpress-catalog-manual-pilot.yml',
      '.github/workflows/staging-aliexpress-catalog-pilot-audit.yml',
      '.github/workflows/staging-aliexpress-catalog-publish-pilot.yml',
      '.github/workflows/staging-aliexpress-pool-integrity.yml',
      '.github/workflows/staging-aliexpress-public-hero-pilot.yml',
      '.github/workflows/staging-aliexpress-refinery-audit.yml',
      '.github/workflows/staging-catalog-ops.yml',
      '.github/workflows/staging-storefront-e2e-audit.yml',
      '.github/workflows/staging-pdp-aliexpress-live-audit.yml',
      '.github/workflows/staging-real-supplier-1000-stress.yml',
      '.github/workflows/isolated-real-cj-1000-catalog-stress.yml',
      '.github/workflows/isolated-cj-refinery-continuation.yml',
      '.github/workflows/isolated-cj-fr-quality-workpack.yml',
      '.github/workflows/isolated-catalog-termium-memory.yml',
      '.github/workflows/isolated-fr-glossary-batch001.yml',
      '.github/workflows/isolated-cj-fr-cold-start-challenge.yml',
      '.github/workflows/isolated-catalog-fr-quality-campaign.yml',
      '.github/workflows/isolated-catalog-refinery-final-acceptance.yml',
    ],
    utils: [
      'utils/categories-cache.js',
    ],
    scripts: [
      'scripts/allegro-sandbox-check.js',
      'scripts/ebay-p3-pipeline-proof.js',
      'scripts/cj-real-showcase-seed.js',
      'scripts/cj-full-catalog-sync.js',
      'scripts/aliexpress-500-catalog-sync.js',
      'scripts/real-supplier-1000-stress-staging.js',
      'scripts/catalog-fr-free-e2e-preparation.js',
      'scripts/cj-broad-catalog-stress-fill.js',
      'scripts/cj-refinery-commandability-continuation.js',
      'scripts/catalog-fr-quality-workpack.js',
      'scripts/catalog-fr-quality-apply.js',
      'scripts/catalog-termium-import.js',
      'scripts/cj-fr-cold-start-challenge.js',
      'scripts/catalog-fr-quality-campaign-audit.js',
      'scripts/catalog-refinery-final-acceptance.js',
    ],
    services: [
      // MISSION 1 (KOMERCE_AUDIT_ABSTRACTIONS_CATALOG_CHANGE_INTAKE) — décideur
      // et écriture contrôlée de synchronisation de stock fournisseur, cf.
      // docs/doctrine/DOCTRINE_CATALOG_CHANGE_INTAKE.md.
      'services/catalog-stock-sync-decision.js',
      'services/catalog-stock-sync-application.js',
      // MISSION 2 — moteur commun décision/application pour title, description,
      // media, purchase_price (écriture réelle) et offer_status/is_active/
      // option_axes/sellable_units (decision-only, jamais d'écriture).
      'services/catalog-field-sync-decision.js',
      'services/catalog-field-sync-application.js',
      'services/suppliers/allegro-sandbox-client.js',
      'services/suppliers/connectors/allegro-connector.js',
      'services/suppliers/connectors/ebay-connector.js',
      'services/product-publication-guard.js',
      'services/catalog-media-visual-fr-proof.js',
      'services/catalog-fr-quality.js',
      'services/catalog-terminology-memory.js',
      'services/product-admin-service.js',
      'services/product-variant-service.js',
      'services/product-sku-service.js',
      'services/product-sellable-service.js',
      'services/product-stock-service.js',
      'services/product-price-audit.js',
      'services/catalog-candidate-product-service.js',
      'services/catalog-product-mutation-service.js',
      'services/catalog-change-intake.js',
      'services/catalog-provider-capability-contract.js',
      'services/catalog-promotion.js',
      'services/catalog-promotion/axes.js',
      'services/catalog-promotion/sku.js',
      'services/catalog-promotion/sku-media.js',
      'services/catalog-promotion/content.js',
      'services/suppliers/normalized-product.js',
      'services/suppliers/json-source-pipeline.js',
      'services/suppliers/pipeline-constants.js',
      'services/suppliers/media-normalizer.js',
      'services/suppliers/promotion-classifier.js',
      'services/suppliers/source-product-normalizer.js',
      'services/catalog-market-exposure-service.js',
      'services/suppliers/connectors/api-connector.base.js',
      'services/suppliers/connectors/manual-connector.js',
      'services/suppliers/connectors/csv-connector.js',
      'services/suppliers/connectors/_connector-utils.js',
      'services/suppliers/connectors/noon-connector.js',
      'services/suppliers/connectors/cj-connector.js',
      'services/suppliers/aliexpress-oauth.js',
      'services/suppliers/connectors/aliexpress-connected-connector.js',
      'services/suppliers/connectors/aliexpress-connector.js',
      'services/suppliers/connectors/json-connector.js',
      'services/suppliers/cj-catalog-index.js',
      'services/suppliers/catalog-sync-checkpoint.js',
      'services/supplier-catalog-scanner.js',
      'services/suppliers/catalog-import-orchestrator.js',
      'services/sourcing-import-dispatch.js',
      'services/suppliers/catalog-import-json.js',
      'services/catalog-eligibility.js',
      'services/catalog-public-view.js',
      'services/catalog-product-route-canary.js',
      'services/catalog-product-source-read-service.js',
      'services/catalog-product-detail.js',
      'services/catalog-enrichment.js',
      'services/prompts/catalog-enrichment.prompt.js',
      'services/catalog-overrides.js',
      'services/catalog-approval.js',
      'services/boutique-taxonomy-admin.js',
      'services/catalog-workspace.js',
      'services/catalog-live-flow.js',
      'services/catalog-workspace-live-composer.js',
    ],
    schemas: [
      'schemas/catalog/normalized-supplier-product.v1.schema.json',
      'schemas/catalog/normalized-supplier-product.v2.schema.json',
      'schemas/catalog/product-detail.v1.schema.json',
      'schemas/catalog/import-profile.v1.schema.json',
    ],
    migrations: [
      'migrations/242_catalog_field_sync_state.sql',
      'migrations/241_catalog_stock_sync_state.sql',
      'migrations/098_catalog_refinery_foundation.sql',
      'migrations/100_catalog_enrichment_runs.sql',
      'migrations/101_variant_images.sql',
      'migrations/104_product_skus.sql',
      'migrations/105_catalog_source_contract_v2.sql',
      'migrations/106_catalog_media.sql',
      'migrations/107_product_variants_axis_display_name.sql',
      'migrations/108_product_skus_supplier_identity.sql',
      'migrations/109_product_sku_media.sql',
      'migrations/110_catalog_import_audit.sql',
      'migrations/130_deactivate_catalog_test_placeholders.sql',
      'migrations/150_catalog_import_business_ref.sql',
      'migrations/147_catalog_global_access_grants.sql',
      'migrations/163_supplier_catalog_sync_checkpoints.sql',
      'migrations/202_catalog_product_market_exposure.sql',
      'migrations/206_catalog_product_market_exposure_snapshot.sql',
      'migrations/218_supplier_oauth_connections.sql',
    ],
    config: [
      'config/import-profiles/komerce-test-dummyjson.v1.json',
    ],
    docs: [
      'docs/doctrine/DOCTRINE_CATALOGUE.md',
      'docs/doctrine/DOCTRINE_CATALOG_CHANGE_INTAKE.md',
      'docs/doctrine/DOCTRINE_INGESTION_CATALOGUE.md',
      'docs/doctrine/DOCTRINE_PRODUCT_DETAIL_CONTRACT.md',
      'docs/specs/DECISION_MODELE_STOCK_SKU.md',
      'docs/CJ_CONNECTOR.md',
      'docs/cj-connector-validation.md',
      'docs/allegro-sandbox.md',
      'docs/cj-real-showcase-63.md',
      'docs/cj-real-showcase-validation.md',
      'docs/cj-real-showcase-runbook.md',
      'docs/cj-real-showcase-63-checklist.md',
      'docs/cj-real-showcase-63-scope.md',
      'docs/catalog/MARKET_PRODUCT_VALIDATION.md',
    ],
    routes: [
      'routes/products.js',
      'routes/catalog-product-detail.js',
      'routes/admin-boutique-categories.js',
      'routes/categories.js',
      'routes/admin/catalog-approval.js',
      'routes/admin-catalog-workspace.js',
      'routes/integrations-aliexpress.js',
    ],
    boutique: [
      'js/b-catalog.js',
      'js/b-catalog-desktop-enhancers.js',
      'js/b-product-open-contract.js',
      'js/product-store.js',
      'js/controllers/home-controller.js',
      'js/render/render-categories.js',
      'js/render/render-home-sections.js',
      'js/render/render-product-card.js',
      'js/view-models/product-card-model.js',
      'js/view-models/product-card-view-model.js',
      'js/b-modal.js',
      'js/b-modal-core.js',
      'js/b-modal-product.js',
      'js/b-modal-image-ux.js',
      'js/b-modal-social-proof.js',
      'js/b-modal-nav.js',
      'js/b-modal-suggestions.js',
      'js/b-modal-cart.js',
      'js/b-modal-product-detail-bootstrap.js',
      'js/b-modal-mobile-product.js',
      'js/b-modal-desktop-product.js',
      'js/b-modal-desktop-enhancers.js',
      'js/b-pdp-curation-suggestions.js',
      'js/view-models/modal-selection-model.js',
      'js/view-models/product-content-model.js',
      'js/shop-schema.js',
      'js/market-hydration.js',
      'js/b-pager.js',
      'js/b-subcat.js',
      'js/b-cart-product-open-style.js',
      'css/hero.css',
      'css/products.css',
      'css/categories.css',
      'css/modal-shell.css',
      'css/modal-media.css',
      'css/modal-product.css',
      'css/modal-product-lot4-hybrid.css',
      'css/modal-mobile-canonical.css',
      'css/modal-enriched-content.css',
    ],
    dash: [
      'dashboards/admin/js/views/SuppliersView.js',
      'dashboards/admin/js/views/SourcingView.js',
      'dashboards/admin/js/views/SourcingScannerView.js',
      'dashboards/admin/js/views/CatalogApprovalView.js',
    ],
    tests: [
      'tests/integration/catalog-field-sync-decision-catalog-field-sync-application-real-db.test.js',
      'tests/integration/catalog-stock-sync-decision-real-db.test.js',
      'tests/integration/catalog-stock-sync-application-real-db.test.js',
      'tests/integration/catalog-stock-sync-concurrency-real-db.test.js',
      'tests/integration/catalog-approval-queue-contract.test.js',
      'tests/unit/allegro-sandbox-client.test.js',
      'tests/unit/allegro-connector.test.js',
      'tests/unit/allegro-accept-language.test.js',
      'tests/unit/allegro-contract-only.test.js',
      'tests/unit/allegro-conversation-requiredness.test.js',
      'tests/unit/allegro-golden-customer-checkout-proof.test.js',
      'tests/unit/allegro-golden-prebuyer-proof.test.js',
      'tests/unit/allegro-golden-preflight-contract.test.js',
      'tests/unit/allegro-offer-prerequisites-proof.test.js',
      'tests/unit/allegro-offer-prerequisites.test.js',
      'tests/unit/allegro-sandbox-safe-errors.test.js',
      'tests/unit/allegro-sandbox-shipping-rate-sanitization.test.js',
      'tests/unit/allegro-shipping-contract-client.test.js',
      'tests/unit/allegro-shipping-rate-contract.test.js',
      'tests/unit/ebay-connector.test.js',
      'tests/unit/ebay-p3-pipeline-proof.test.js',
      'tests/unit/allegro-sandbox-check.test.js',
      'tests/unit/admin-boutique-categories.test.js',
      'tests/unit/catalog-product-route-canary-http.test.js',
      'tests/unit/catalog-product-source-read-service.test.js',
      'tests/unit/api-connector-base.test.js',
      'tests/unit/categories-cache.test.js',
      'tests/unit/categories.test.js',
      'tests/unit/connector-utils.test.js',
      'tests/unit/csv-connector.test.js',
      'tests/unit/manual-connector.test.js',
      'tests/unit/manual-connector-source-v2.test.js',
      'tests/unit/noon-connector.test.js',
      'tests/unit/cj-connector.test.js',
      'tests/unit/aliexpress-connector.test.js',
      'tests/unit/aliexpress-oauth.test.js',
      'tests/unit/aliexpress-500-catalog-sync.test.js',
      'tests/unit/aliexpress-500-catalog-topup.test.js',
      'tests/unit/aliexpress-feed-surface-proof.test.js',
      'tests/unit/aliexpress-feed-topup-runtime.test.js',
      'tests/unit/aliexpress-fulfillment-adapter.test.js',
      'tests/unit/aliexpress-golden-e2e.test.js',
      'tests/unit/aliexpress-golden-repair-existing.test.js',
      'tests/unit/aliexpress-golden-semantic.test.js',
      'tests/unit/aliexpress-native-sku-identity.test.js',
      'tests/unit/aliexpress-promote-authority-regression.test.js',
      'tests/unit/aliexpress-promote-drafts-staging.test.js',
      'tests/unit/aliexpress-promote-source-only.test.js',
      'tests/unit/aliexpress-refinery-audit-staging.test.js',
      'tests/unit/aliexpress-refinery-rescan-staging.test.js',
      'tests/unit/aliexpress-refresh-imported-contracts.test.js',
      'tests/unit/aliexpress-wave2-completion-smoke.test.js',
      'tests/unit/aliexpress-wave2-completion.test.js',
      'tests/unit/aliexpress-wave2-feed-surface.test.js',
      'tests/unit/aliexpress-wave2-sourcing.test.js',
      'tests/unit/cj-real-showcase-taxonomy-repair.test.js',
      'tests/unit/promote-showcase-imagekit-staging.test.js',
      'tests/unit/showcase-catalog.test.js',
      'tests/unit/showcase-curate-staging-500-hybrid.test.js',
      'tests/unit/showcase-curate-staging-500-primary.test.js',
      'tests/unit/showcase-curate-staging-500.test.js',
      'tests/unit/showcase-imagekit-v2.test.js',
      'tests/unit/showcase-media-audit-retry.test.js',
      'tests/unit/showcase-media-mirror.test.js',
      'tests/unit/showcase-media-provider.test.js',
      'tests/unit/showcase-rebalance-staging-500.test.js',
      'tests/unit/showcase-source-build.test.js',
      'tests/unit/showcase-v2-media-realism.test.js',
      'tests/unit/showcase-v2-plan.test.js',
      'tests/unit/showcase-v2-reset.test.js',
      'tests/unit/showcase-v2-source-build.test.js',
      'tests/unit/cj-connector-doc-contract.test.js',
      'tests/unit/cj-real-showcase-seed.test.js',
      'tests/unit/cj-catalog-index.test.js',
      'tests/unit/cj-full-catalog-sync.test.js',
      'tests/unit/catalog-candidate-product-service.test.js',
      'tests/unit/catalog-product-mutation-service.test.js',
      'tests/unit/catalog-change-intake.test.js',
      'tests/unit/catalog-provider-capability-contract.test.js',
      'tests/unit/catalog-promotion.test.js',
      'tests/unit/catalog-promotion-axes.test.js',
      'tests/unit/catalog-promotion-sku.test.js',
      'tests/unit/catalog-promotion-sku-media.test.js',
      'tests/unit/catalog-promotion-content.test.js',
      'tests/unit/catalog-promotion-content-db.test.js',
      'tests/unit/normalized-product.test.js',
      'tests/unit/normalized-product-source-contract-v2.test.js',
      'tests/unit/product-admin-service.test.js',
      'tests/unit/product-variant-service.test.js',
      'tests/unit/product-sku-service.test.js',
      'tests/unit/product-sellable-service.test.js',
      'tests/unit/product-stock-service.test.js',
      'tests/unit/product-price-audit.test.js',
      'tests/unit/product-publication-guard.test.js',
      'tests/unit/catalog-media-visual-fr-proof.test.js',
      'tests/unit/products.test.js',
      // E2E fonctionnel — chantier currency debt (audit 09-2026), LOT 2.
      // products.price_kmf/cost_kmf/unsold_price_kmf (migration 215,
      // integer -> numeric). v_shipment_density dépend de cost_kmf (trouvé
      // par exécution réelle) et agrège une marge à travers 5 tables : le
      // test construit la chaîne complète pour vérifier l'exactitude au
      // centime, pas seulement que la vue reste interrogeable.
      'tests/e2e-api/products.kmf-numeric.e2e.test.js',
      'tests/unit/catalog-product-detail.test.js',
      'tests/unit/catalog-test-placeholder-migration.test.js',
      'tests/unit/modal-mobile-canonical.test.js',
      'tests/unit/supplier-catalog-scanner.test.js',
      'tests/unit/catalog-import-orchestrator.test.js',
      'tests/unit/real-supplier-1000-stress-staging.test.js',
      'tests/unit/catalog-fr-free-e2e-preparation.test.js',
      'tests/unit/cj-broad-catalog-stress-fill.test.js',
      'tests/unit/cj-refinery-commandability-continuation.test.js',
      'tests/unit/catalog-fr-quality.test.js',
      'tests/unit/catalog-fr-quality-workpack.test.js',
      'tests/unit/catalog-fr-quality-apply.test.js',
      'tests/unit/catalog-terminology-memory.test.js',
      'tests/unit/catalog-termium-import.test.js',
      'tests/unit/cj-fr-cold-start-challenge.test.js',
      'tests/unit/catalog-fr-quality-campaign-audit.test.js',
      'tests/unit/catalog-refinery-final-acceptance.test.js',
      'tests/unit/catalog-import-orchestrator-source-v2.test.js',
      'tests/unit/catalog-eligibility.test.js',
      'tests/unit/scan-engine-content-verification.test.js',
      'tests/unit/scan-engine-extras.test.js',
      'tests/unit/catalog-public-view.test.js',
      'tests/unit/catalog-enrichment.test.js',
      'tests/unit/catalog-enrichment-extended.test.js',
      'tests/unit/catalog-enrichment-fixtures.js',
      'tests/unit/catalog-overrides.test.js',
      'tests/integration/catalog-import-json.integration.test.js',
      'tests/unit/json-source-pipeline.test.js',
      'tests/unit/pipeline-constants.test.js',
      'tests/unit/media-normalizer.test.js',
      'tests/unit/promotion-classifier.test.js',
      'tests/unit/source-product-normalizer.test.js',
      'tests/unit/catalog-sync-checkpoint.test.js',
      'tests/unit/json-connector.test.js',
      'tests/unit/catalog-approval.test.js',
      'tests/unit/integrations-aliexpress-route.test.js',
      'tests/unit/catalog-workspace-live-composer.test.js',
      'tests/unit/admin-catalog-approval-route.test.js',
      'tests/unit/catalog-enrichment-editorial-invariants.test.js',
      'tests/unit/catalog-enrichment-error-paths.test.js',
      'tests/unit/catalog-enrichment-uncovered.test.js',
      'tests/unit/catalog-image-health-audit-contract.test.js',
      'tests/unit/catalog-import-eligibility-evidence.test.js',
      'tests/unit/catalog-product-detail-axis-display-name.test.js',
      'tests/unit/catalog-promotion-supplier-order-identity-db.test.js',
      'tests/unit/catalog-promotion-supplier-order-identity.test.js',
      'tests/unit/catalog-promotion-v2-contract.test.js',
      'tests/unit/product-detail-content-schema.test.js',
      'tests/unit/golden-product-content-e2e-seam.test.js',
      'tests/unit/golden-product-gpm1.test.js',
      'tests/unit/normalized-supplier-product-v2-content.test.js',
      'tests/unit/product-skus-supplier-order-identity-migration.test.js',
      'tests/unit/retired-catalog-startup-migrations.test.js',
      'tests/unit/supplier-catalog-scanner-audio-category.test.js',
      'tests/unit/supplier-catalog-scanner-refinery-regression.test.js',
      'tests/unit/staging-catalog-prune.test.js',
      'tests/unit/l1-market-buyer-boundary.test.js',
      'tests/unit/isweep-services.test.js',
      'tests/unit/admin-catalog-workspace-route.test.js',
      'tests/unit/catalog-workspace.test.js',
      'tests/unit/catalog-live-flow.test.js',
      'tests/unit/sourcing-import-dispatch.test.js',
      'tests/unit/boutique-taxonomy-admin.test.js',
      'tests/unit/canonical-catalog-workspace-boundary.test.js',
      'tests/unit/canonical-catalog-authority-boundary.test.js',
      'tests/unit/require-catalog-global-authority.test.js',
      'tests/unit/catalog-market-exposure-service.test.js',
      'tests/unit/catalog-market-exposure-snapshot.test.js',
      'tests/unit/catalog-public-exposure-gate.test.js',
    ],
  },

  repos: {
    backend: 'services/ + routes/ ci-dessus',
    boutique: 'catalogue vivant, cartes produit et modal produit catalogue — gouvernes en detail par docs/boutique/BOUTIQUE_COMPONENT_OWNERSHIP.md et docs/boutique/BOUTIQUE_MODAL_ARCHITECTURE.md',
  },

  db: {
    tables: [
      'boutique_categories: RW',
      'boutique_subcategories: RW',
      'catalog_exclusions: R',
      'catalog_field_overrides: RW',
      'catalog_glossary: R',
      'catalog_terminology_reference: RW',
      'catalog_enrichment_runs: W',
      'catalog_media: RW!',
      'order_items: R',
      'orders: R',
      'product_skus: RW!',
      'product_sku_media: RW!',
      'product_variants: RW!',
      'product_content_profile: RW',
      'product_content_sections: RW',
      'product_market_exposure: RW!',
      'product_attributes: RW',
      'products: RW!',
      'sourcing_candidates: R',
      'supplier_catalog_imports: W',
      'supplier_catalog_sync_checkpoints: RW',
      'supplier_oauth_connections: RW',
    ],
  },

  security: {
    status: 'CONFIRMED_MIXED',
    authedRoutesDetected: 24,
    totalRoutes: 31,
    note: 'Catalogue public en lecture ; OAuth AliExpress expose une callback publique protégée par state et trois routes admin protégées. Les tokens fournisseur sont chiffrés AES-256-GCM et ne sont jamais renvoyés au navigateur.',
  },

  contract: {
    exposes: [
      'GET /api/products',
      'GET /api/products/:id',
      'GET /api/products/:id/detail',
      'GET /api/admin/catalog/approval-queue',
      'POST /api/admin/catalog/approval-queue/:id/approve',
      'POST /api/admin/catalog/approval-queue/:id/reject',
      'POST /api/admin/catalog/approval-queue/:id/override',
      'GET /api/admin/boutique-categories',
      'POST /api/admin/boutique-categories',
      'DELETE /api/admin/boutique-categories/:key',
      'GET /api/admin/boutique-categories/:key',
      'PUT /api/admin/boutique-categories/:key',
      'GET /api/admin/boutique-categories/:key/subcategories',
      'POST /api/admin/boutique-categories/:key/subcategories',
      'DELETE /api/admin/boutique-categories/:key/subcategories/:subKey',
      'PUT /api/admin/boutique-categories/:key/subcategories/:subKey',
      'GET /api/categories',
      'POST /api/products',
      'DELETE /api/products/:id',
      'PUT /api/products/:id',
      'POST /api/products/:id/image',
      'POST /api/products/:id/images',
      'GET /api/products/:id/variants',
      'PUT /api/products/:id/variants',
      'DELETE /api/products/:id/variants/:variantId',
      'GET /api/products/:id/skus',
      'GET /api/products/:id/skus/readiness',
      'POST /api/products/:id/skus',
      'DELETE /api/products/:id/skus/:skuId',
      'GET /api/products/categories',
      'GET /api/products/subcategories',
      'GET /api/admin/workspaces/catalog',
      'POST /api/admin/workspaces/catalog/approval/:productRef/approve',
      'POST /api/admin/workspaces/catalog/approval/:productRef/override',
      'POST /api/admin/workspaces/catalog/approval/:productRef/reject',
      'POST /api/admin/workspaces/catalog/categories',
      'POST /api/admin/workspaces/catalog/categories/:key/deactivate',
      'POST /api/admin/workspaces/catalog/categories/:key/subcategories',
      'POST /api/admin/workspaces/catalog/categories/:key/subcategories/:subKey/deactivate',
      'POST /api/admin/workspaces/catalog/categories/:key/subcategories/:subKey/update',
      'POST /api/admin/workspaces/catalog/categories/:key/update',
      'POST /api/admin/workspaces/catalog/products',
      'POST /api/admin/workspaces/catalog/products/:productRef/deactivate',
      'POST /api/admin/workspaces/catalog/products/:productRef/update',
      'POST /api/integrations/aliexpress/oauth/refresh',
      'GET /api/integrations/aliexpress/oauth/start',
      'GET /api/integrations/aliexpress/status',
    ],
    internalApi: [
      { fn: 'createDraftFromSourcingCandidate', file: 'services/product-admin-service.js' },
      { fn: 'createDraftProductFromSourcingCandidate', file: 'services/catalog-candidate-product-service.js' },
      { fn: 'applyPrice', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'updateSourcingFields', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'bulkAssignSourcingRail', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'replaceVariantsForSourcing', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'maybeApplyCatalogProductRouteCanary', file: 'services/catalog-product-route-canary.js' },
      { fn: 'readCatalogProductSource', file: 'services/catalog-product-source-read-service.js' },
      { fn: 'resolveCatalogProductReadMode', file: 'services/catalog-product-source-read-service.js' },
    ],
    consumes: [
      'external-provider-contracts (contrat transverse de preuve provider : Conversation + KNOWN/DERIVED/UNKNOWN + P0..P4 consommé par les scripts Allegro catalog)',
      'sourcing (API internes findCanonicalProductIdsForCatalogProduct, collectCanonicalProductProjectionById et applyCanonicalSourceReadSeam)',
      'notifications (alert persistence via utils/alerts.js)',
      'auth-identity (projection boutique b-greeting consomme /api/auth/me pour personnaliser la surface catalogue)',
      'platform-ops (monitoring/exploitation transverse observé dans le code)',
      'infrastructure (dépendance technique transversale observée : DB, logger, helpers ou bootstrap possédés par infrastructure)',
      "business-rules (FF-C1 2026-07-29 — lecture du référentiel de règles métier ; preuve: services/suppliers/catalog-import-orchestrator.js -> utils/rules.js ; services/catalog-product-detail.js -> utils/rules.js ; services/catalog-enrichment.js -> utils/rules.js)",
      'economic-engine (prix produit, valorisation commerciale transport et audit price_history propriétaire)',
      'market-autonomy (résolution buyer du prix LOCAL_ACTIVE par marché ; le catalogue reste propriétaire du produit global)',
      'sourcing (persistence lifecycle sourcing_candidates et sourcing_candidate_events via sourcing-candidate-import-service ; catalog n execute plus de SQL direct sur ces tables)',
      'supplier-connectivity (Supplier Order Identity canonique : catalog persiste et valide l’identité commandable via services/suppliers/supplier-order-identity.js ; aucun payload fournisseur n’est réinterprété par heuristique)',
      'purchasing (scripts/allegro-sandbox-check.js compose l adapter Allegro fulfillment possédé par Purchasing pour la preuve sandbox ; aucune autorité Purchasing n est recopiée dans Catalogue)',
      'logistics (rails et eligibilite transport ; le catalog ne decide jamais le rail)',
      'shared-cart (ne pas reutiliser la modal catalogue pour la fiche snapshot)',
      'auth',
      'orders (actions panier depuis les surfaces produit boutique — preuve: b-catalog.js, render-product-card.js, b-modal-desktop-product.js, b-subcat.js, b-favs.js, b-modal-buybox-shared.js (+ tests) -> b-cart-core.js/b-cart.js, propriete orders-client canonicalFeature:orders)',
    ],
  },

  debt: {
    knownGaps: [
      {
        gap: 'contrat historique POST /api/admin/products/:id/publish : aucune route ne le sert. Depuis K-4, la publication se fait par la file d approbation.',
        risk: 'aucun — mecanisme remplace et couvert ; retirer toute reference historique restante lorsqu elle est rencontree.',
      },
      {
        gap: 'le contrat fournisseur V2 preserve media[], option_axes[] et sellable_units[] dans sourcing_candidates.normalized_source_contract, mais ces faits source ne sont pas encore promus vers les structures canoniques produit/media/options/SKU.',
        risk: 'GET /api/products/:id/detail v1 projette honnêtement les donnees canoniques actuelles products/product_variants/product_skus ; les roles source riches comme SCENE restent donc indisponibles tant que la promotion source vers catalogue n est pas explicite.',
      },
      {
        gap: 'le contrat detail v1 expose les rails deja commercialement exposes avec price_kmf reel (services/transport-pricing.js, quantity=1, poids/volume produit) depuis le chantier §9. eta_label reste null : aucune table ne relie un delai a SEA_STANDARD/AIR_EXPRESS (la table carriers existe mais c est un seed d exemple generique Dubai->Moroni, sans FK vers les rails, explicitement marque "a adapter avant la mise en prod").',
        risk: 'price_kmf est fiable (memes business_rules que orders/create.js) et retombe honnetement a null si le produit n a pas de weight_kg ou si le tarif est absent. eta_label reste interdit d affichage tant qu aucune decision business ne fournit un delai reel par rail ; interdiction de retomber sur Gratuit ou 3 a 5 semaines code en frontend.',
      },
      {
        gap: 'b-modal-core.js lance encore le fetch variantes legacy et modal-view-model.js reste necessaire pour des classes structurelles historiques.',
        risk: 'un guard de repaint transitoire protege PDC-4/PDC-5 ; PDC-6 doit supprimer le fetch legacy, l alias bootstrap mobile et les derniers owners structurels devenus inutiles.',
      },
    ],
  },

  authority: 'backend-core — normalized-product possede le contrat source versionne ; catalog possede le catalogue canonique et le contrat detail public ; toute modification modal catalogue suit DOCTRINE_PRODUCT_DETAIL_CONTRACT.md et docs/boutique/BOUTIQUE_MODAL_ARCHITECTURE.md',

  invariants: [
    'un produit publie a toujours passe product-publication-guard.js',
    { statement: 'products.price_kmf/cost_kmf/unsold_price_kmf (numeric depuis la migration 215) conservent leurs centimes et v_shipment_density calcule une marge exacte au centime à travers sa chaîne à 5 tables',
      test: 'tests/e2e-api/products.kmf-numeric.e2e.test.js' },
    'jamais de creation produit par formulaire vide : tout entre par un connecteur (le manuel EST un connecteur)',
    'la donnee source ne se perd jamais : raw_payload reste le brut integral et normalized_source_contract preserve separement le mapping V2 valide',
    'une structure riche connue ne doit pas etre aplatie puis reconstruite par heuristique ; une source pauvre reste pauvre honnêtement',
    'toute retouche manuelle est un override trace (catalog_field_overrides), jamais une edition de la fiche generee',
    'la boutique ne lit que les champs publies : les champs de cuisine source/content_source/normalized_source_contract lui sont invisibles',
    'une unite vendable = un SKU ; product_variants decrit les axes et ne porte pas la verite de stock cible',
    'GET /api/products/:id/detail retourne un contrat v1 valide par schema ; un produit legacy expose ses axes mais aucune fausse sellable_unit',
    'le contrat detail compose des faits et resultats proprietaires ; il ne recalcule ni pricing ni routing ni eligibilite rail',
    'delivery_options contient uniquement les rails deja commercialement exposes par logistics ; absence de prix ou ETA reste null tant qu aucun moteur proprietaire ne les fournit',
    'le frontend ne decide jamais d un rail ni d un delai universel de livraison',
    'mobile et desktop chargent le meme contrat detail et consomment le meme etat de selection SKU',
    'un seul owner derive disponibilite et media courants ; les renderers responsive ne font que composer',
    'b-modal-desktop-enhancers ne calcule ni prix ni stock ni livraison ni sous-total',
    'le prompt d enrichissement est du code : versionne dans le depot, chaque run trace, un echec IA ne bloque jamais un import',
    'la modal produit affiche le catalogue vivant et ne doit pas servir de fiche snapshot panier partage',
    'le parcours mobile Voir en grand appartient a b-modal-image-ux.js et modal-media.css',
    'aucune fiche candidate issue du pipeline ne passe lifecycle_status=active sans etre passee par la file d approbation, meme si needs_review est faux',
    'le pool fournisseur CJ de la Raffinerie ne dépasse jamais 1000 références propres ; son alimentation ne publie aucun produit automatiquement',
    'la source AliExpress reste une entrée de Raffinerie : elle ne crée ni ne publie jamais directement un produit canonique',
    'le pool AliExpress staging ne dépasse jamais 500 références propres en stock et ne peut pas s exécuter en production',
    'les access/refresh tokens fournisseur sont persistés chiffrés ; l App Secret reste uniquement en variable serveur et aucun token n est exposé au navigateur',
  ],
};
