/**
 * @feature       catalog
 * @type          feature
 * @domain        catalog
 * @status        production
 * @owner         backend-core
 * @since         2025-09
 * @doctrine      docs/doctrine/FEATURE_DOCTRINE.md
 * @registry      docs/doctrine/APP_FEATURE_REGISTRY.md
 */
'use strict';

module.exports = {
  name:     'catalog',
  nature:   'feature',   // feature | capability | governance-unit
  type:     'feature',
  domain:   'catalog',
  status:   'production',
  owner:    'backend-core',

  classification: {
    axis:     'business',
    kind:     'business-feature',
    rationale: [
      'Propriétaire exclusif de products, catalog_media, product_variants, product_skus, product_sku_media, et des règles de canonicalisation, dédoublonnage et publication (arbitrage D, 2026-07-29).',
      "possède le contrat produit public, le lifecycle de publication et la vérité SKU/media ; pricing, routing et ranking restent consommés depuis leurs features propriétaires",
    ],
  },
  since:    '2025-09',
  doctrine: 'docs/doctrine/FEATURE_DOCTRINE.md',

  service: 'Raffiner les donnees fournisseur en catalogue canonique, publier les unites vendables et exposer un contrat detail produit stable a la Boutique.',

  perimeter: {
    in: [
      'connecteurs fournisseurs (CSV, API, manuel, Noon, CJdropshipping)',
      'contrat source fournisseur versionne V1/V2 : brut integral + preservation explicite media, axes et unites vendables quand la source les connait',
      'publication produit et déclenchement de l audit prix via economic-engine',
      'categories boutique admin',
      'catalogue vivant Boutique : grille, cartes produit, ouverture fiche produit',
      'catalogue canonique : produit, medias publics, axes d options descriptifs et unites vendables SKU',
      'contrat detail produit public v1 : identity, pricing, media, option_axes, sellable_units et delivery_options deja resolues par leurs autorites',
      'projection des rails de livraison deja commercialement exposes par logistics, sans inventer prix ni delai',
      'modal produit catalogue : un fetch Product Detail, un etat de selection SKU, deux compositions responsive mobile/desktop',
      'raffinerie catalogue : donnee source EN conservee, eligibilite douane/transport (catalog_exclusions), enrichissement FR, overrides traces, approbation humaine unique',
      'glossaire metier EN->FR (catalog_glossary)',
      'file d approbation admin (etage 6) : approve/reject/override en un ecran, seul point de validation humaine avant lifecycle_status=active',
      'bootstrap visuel CJ borné : 63 produits réels, médias fournisseur liés au lignage, exécution one-shot gardée',
      'pool CJ de Raffinerie borné à 1000 références propres maximum, dédupliqué et reprenable, sans publication automatique',
    ],
    out: [
      'calcul du prix final et valorisation transport (feature economic-engine)',
      'decision de rail, routing et eligibilite logistique dynamique (feature logistics)',
      'mise en avant / classement (feature recommendations)',
      'fiche snapshot lecture seule du panier partage (feature shared-cart)',
      'checkout final et paiement (features orders/payments)',
    ],
  },

  files: {
    middleware: [
      'middleware/require-catalog-global-authority.js',
    ],
    ci: [
      '.github/workflows/showcase-v2-staging-deploy.yml',
      '.github/workflows/cj-real-showcase-contract.yml',
      '.github/workflows-disabled/showcase-catalog-media-audit.yml',
      '.github/workflows-disabled/showcase-catalog-staging-deploy.yml',
      '.github/workflows-disabled/README-CJ-SHOWCASE.md',
    ],
    utils: [
      'utils/categories-cache.js',
    ],
    scripts: [
      'scripts/cj-real-showcase-seed.js',
      'scripts/cj-full-catalog-sync.js',
    ],
    services: [
      'services/product-publication-guard.js',
      'services/product-admin-service.js',
      'services/product-variant-service.js',
      'services/product-sku-service.js',
      'services/product-sellable-service.js',
      'services/product-stock-service.js',
      'services/product-price-audit.js',
      'services/catalog-candidate-product-service.js',
      'services/catalog-product-mutation-service.js',
      'services/catalog-promotion.js',
      'services/catalog-promotion/axes.js',
      'services/catalog-promotion/sku.js',
      'services/catalog-promotion/sku-media.js',
      'services/catalog-promotion/content.js',
      'services/suppliers/normalized-product.js',
      'services/suppliers/json-source-pipeline.js',
      'services/suppliers/pipeline-constants.js',
      'services/suppliers/media-normalizer.js',
      'services/suppliers/promotion-classifier.js',
      'services/suppliers/source-product-normalizer.js',
      'services/suppliers/connectors/api-connector.base.js',
      'services/suppliers/connectors/manual-connector.js',
      'services/suppliers/connectors/csv-connector.js',
      'services/suppliers/connectors/_connector-utils.js',
      'services/suppliers/connectors/noon-connector.js',
      'services/suppliers/connectors/cj-connector.js',
      'services/suppliers/connectors/json-connector.js',
      'services/suppliers/cj-catalog-index.js',
      'services/suppliers/catalog-sync-checkpoint.js',
      'services/supplier-catalog-scanner.js',
      'services/suppliers/catalog-import-orchestrator.js',
      'services/sourcing-import-dispatch.js',
      'services/suppliers/catalog-import-json.js',
      'services/catalog-eligibility.js',
      'services/catalog-public-view.js',
      'services/catalog-product-detail.js',
      'services/catalog-enrichment.js',
      'services/prompts/catalog-enrichment.prompt.js',
      'services/catalog-overrides.js',
      'services/catalog-approval.js',
      'services/boutique-taxonomy-admin.js',
      'services/catalog-workspace.js',
    ],
    schemas: [
      'schemas/catalog/normalized-supplier-product.v1.schema.json',
      'schemas/catalog/normalized-supplier-product.v2.schema.json',
      'schemas/catalog/product-detail.v1.schema.json',
      'schemas/catalog/import-profile.v1.schema.json',
    ],
    migrations: [
      'migrations/098_catalog_refinery_foundation.sql',
      'migrations/100_catalog_enrichment_runs.sql',
      'migrations/101_variant_images.sql',
      'migrations/104_product_skus.sql',
      'migrations/105_catalog_source_contract_v2.sql',
      'migrations/106_catalog_media.sql',
      'migrations/107_product_variants_axis_display_name.sql',
      'migrations/108_product_skus_supplier_identity.sql',
      'migrations/109_product_sku_media.sql',
      'migrations/110_catalog_import_audit.sql',
      'migrations/130_deactivate_catalog_test_placeholders.sql',
      'migrations/150_catalog_import_business_ref.sql',
      'migrations/147_catalog_global_access_grants.sql',
      'migrations/163_supplier_catalog_sync_checkpoints.sql',
    ],
    config: [
      'config/import-profiles/komerce-test-dummyjson.v1.json',
    ],
    docs: [
      'docs/doctrine/DOCTRINE_CATALOGUE.md',
      'docs/doctrine/DOCTRINE_INGESTION_CATALOGUE.md',
      'docs/doctrine/DOCTRINE_PRODUCT_DETAIL_CONTRACT.md',
      'docs/specs/DECISION_MODELE_STOCK_SKU.md',
      'docs/CJ_CONNECTOR.md',
      'docs/cj-connector-validation.md',
      'docs/cj-real-showcase-63.md',
      'docs/cj-real-showcase-validation.md',
      'docs/cj-real-showcase-runbook.md',
      'docs/cj-real-showcase-63-checklist.md',
      'docs/cj-real-showcase-63-scope.md',
    ],
    routes: [
      'routes/products.js',
      'routes/catalog-product-detail.js',
      'routes/admin-boutique-categories.js',
      'routes/categories.js',
      'routes/admin/catalog-approval.js',
      'routes/admin-catalog-workspace.js',
    ],
    boutique: [
      'js/b-catalog.js',
      'js/b-catalog-desktop-enhancers.js',
      'js/b-product-open-contract.js',
      'js/product-store.js',
      'js/controllers/home-controller.js',
      'js/render/render-categories.js',
      'js/render/render-home-sections.js',
      'js/render/render-product-card.js',
      'js/view-models/product-card-model.js',
      'js/view-models/product-card-view-model.js',
      'js/b-modal.js',
      'js/b-modal-core.js',
      'js/b-modal-product.js',
      'js/b-modal-image-ux.js',
      'js/b-modal-social-proof.js',
      'js/b-modal-nav.js',
      'js/b-modal-suggestions.js',
      'js/b-modal-cart.js',
      'js/b-modal-product-detail-bootstrap.js',
      'js/b-modal-mobile-product.js',
      'js/b-modal-desktop-product.js',
      'js/b-modal-desktop-enhancers.js',
      'js/b-pdp-curation-suggestions.js',
      'js/view-models/modal-selection-model.js',
      'js/view-models/product-content-model.js',
      'js/shop-schema.js',
      'js/market-hydration.js',
      'js/b-pager.js',
      'js/b-subcat.js',
      'js/b-cart-product-open-style.js',
      'css/hero.css',
      'css/products.css',
      'css/categories.css',
      'css/modal-shell.css',
      'css/modal-media.css',
      'css/modal-product.css',
      'css/modal-product-lot4-hybrid.css',
      'css/modal-mobile-canonical.css',
      'css/modal-enriched-content.css',
    ],
    dash: [
      'dashboards/admin/js/views/SuppliersView.js',
      'dashboards/admin/js/views/SourcingView.js',
      'dashboards/admin/js/views/SourcingScannerView.js',
      'dashboards/admin/js/views/CatalogApprovalView.js',
    ],
    tests: [
      'tests/unit/admin-boutique-categories.test.js',
      'tests/unit/api-connector-base.test.js',
      'tests/unit/categories-cache.test.js',
      'tests/unit/categories.test.js',
      'tests/unit/connector-utils.test.js',
      'tests/unit/csv-connector.test.js',
      'tests/unit/manual-connector.test.js',
      'tests/unit/manual-connector-source-v2.test.js',
      'tests/unit/noon-connector.test.js',
      'tests/unit/cj-connector.test.js',
      'tests/unit/cj-connector-doc-contract.test.js',
      'tests/unit/cj-real-showcase-seed.test.js',
      'tests/unit/cj-catalog-index.test.js',
      'tests/unit/cj-full-catalog-sync.test.js',
      'tests/unit/catalog-candidate-product-service.test.js',
      'tests/unit/catalog-product-mutation-service.test.js',
      'tests/unit/catalog-promotion.test.js',
      'tests/unit/catalog-promotion-axes.test.js',
      'tests/unit/catalog-promotion-sku.test.js',
      'tests/unit/catalog-promotion-sku-media.test.js',
      'tests/unit/catalog-promotion-content.test.js',
      'tests/unit/catalog-promotion-content-db.test.js',
      'tests/unit/normalized-product.test.js',
      'tests/unit/normalized-product-source-contract-v2.test.js',
      'tests/unit/product-admin-service.test.js',
      'tests/unit/product-variant-service.test.js',
      'tests/unit/product-sku-service.test.js',
      'tests/unit/product-sellable-service.test.js',
      'tests/unit/product-stock-service.test.js',
      'tests/unit/product-price-audit.test.js',
      'tests/unit/product-publication-guard.test.js',
      'tests/unit/products.test.js',
      'tests/unit/catalog-product-detail.test.js',
      'tests/unit/catalog-test-placeholder-migration.test.js',
      'tests/unit/modal-mobile-canonical.test.js',
      'tests/unit/supplier-catalog-scanner.test.js',
      'tests/unit/catalog-import-orchestrator.test.js',
      'tests/unit/catalog-import-orchestrator-source-v2.test.js',
      'tests/unit/catalog-eligibility.test.js',
      'tests/unit/scan-engine-content-verification.test.js',
      'tests/unit/scan-engine-extras.test.js',
      'tests/unit/catalog-public-view.test.js',
      'tests/unit/catalog-enrichment.test.js',
      'tests/unit/catalog-enrichment-extended.test.js',
      'tests/unit/catalog-enrichment-fixtures.js',
      'tests/unit/catalog-overrides.test.js',
      'tests/integration/catalog-import-json.integration.test.js',
      'tests/unit/json-source-pipeline.test.js',
      'tests/unit/json-connector.test.js',
      'tests/unit/catalog-approval.test.js',
      'tests/unit/admin-catalog-workspace-route.test.js',
      'tests/unit/catalog-workspace.test.js',
      'tests/unit/sourcing-import-dispatch.test.js',
      'tests/unit/boutique-taxonomy-admin.test.js',
      'tests/unit/canonical-catalog-workspace-boundary.test.js',
      'tests/unit/canonical-catalog-authority-boundary.test.js',
      'tests/unit/require-catalog-global-authority.test.js',
    ],
  },

  repos: {
    backend: 'services/ + routes/ ci-dessus',
    boutique: 'catalogue vivant, cartes produit et modal produit catalogue — gouvernes en detail par docs/boutique/BOUTIQUE_COMPONENT_OWNERSHIP.md et docs/boutique/BOUTIQUE_MODAL_ARCHITECTURE.md',
  },

  db: {
    tables: [
      'boutique_categories: RW',
      'boutique_subcategories: RW',
      'catalog_exclusions: R',
      'catalog_field_overrides: RW',
      'catalog_glossary: R',
      'catalog_enrichment_runs: W',
      'catalog_media: RW!',
      'order_items: R',
      'orders: R',
      'product_skus: RW!',
      'product_sku_media: RW!',
      'product_variants: RW!',
      'product_content_profile: RW',
      'product_content_sections: RW',
      'product_attributes: RW',
      'products: RW!',
      'sourcing_candidates: R',
      'supplier_catalog_imports: W',
      'supplier_catalog_sync_checkpoints: RW',
    ],
  },

  security: {
    status: 'CONFIRMED_MIXED',
    authedRoutesDetected: 21,
    totalRoutes: 27,
    note: 'Catalogue public en lecture ; GET /api/products/:id/detail expose uniquement le contrat detail v1 valide. Les contrats source et normalized_source_contract restent internes ; mutations produit, SKU, overrides et approbation restent protegees admin.',
  },

  contract: {
    exposes: [
      'GET /api/products',
      'GET /api/products/:id',
      'GET /api/products/:id/detail',
      'GET /api/admin/catalog/approval-queue',
      'POST /api/admin/catalog/approval-queue/:id/approve',
      'POST /api/admin/catalog/approval-queue/:id/reject',
      'POST /api/admin/catalog/approval-queue/:id/override',
      'GET /api/admin/boutique-categories',
      'POST /api/admin/boutique-categories',
      'DELETE /api/admin/boutique-categories/:key',
      'GET /api/admin/boutique-categories/:key',
      'PUT /api/admin/boutique-categories/:key',
      'GET /api/admin/boutique-categories/:key/subcategories',
      'POST /api/admin/boutique-categories/:key/subcategories',
      'DELETE /api/admin/boutique-categories/:key/subcategories/:subKey',
      'PUT /api/admin/boutique-categories/:key/subcategories/:subKey',
      'GET /api/categories',
      'POST /api/products',
      'DELETE /api/products/:id',
      'PUT /api/products/:id',
      'POST /api/products/:id/image',
      'POST /api/products/:id/images',
      'GET /api/products/:id/variants',
      'PUT /api/products/:id/variants',
      'DELETE /api/products/:id/variants/:variantId',
      'GET /api/products/:id/skus',
      'GET /api/products/:id/skus/readiness',
      'POST /api/products/:id/skus',
      'DELETE /api/products/:id/skus/:skuId',
      'GET /api/products/categories',
      'GET /api/products/subcategories',
    ],
    internalApi: [
      { fn: 'createDraftFromSourcingCandidate', file: 'services/product-admin-service.js' },
      { fn: 'createDraftProductFromSourcingCandidate', file: 'services/catalog-candidate-product-service.js' },
      { fn: 'applyPrice', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'updateSourcingFields', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'bulkAssignSourcingRail', file: 'services/catalog-product-mutation-service.js' },
      { fn: 'replaceVariantsForSourcing', file: 'services/catalog-product-mutation-service.js' },
    ],
    consumes: [
      'notifications (alert persistence via utils/alerts.js)',
      'auth-identity (projection boutique b-greeting consomme /api/auth/me pour personnaliser la surface catalogue)',
      'platform-ops (monitoring/exploitation transverse observé dans le code)',
      'infrastructure (dépendance technique transversale observée : DB, logger, helpers ou bootstrap possédés par infrastructure)',
      "business-rules (FF-C1 2026-07-29 — lecture du référentiel de règles métier ; preuve: services/suppliers/catalog-import-orchestrator.js -> utils/rules.js ; services/catalog-product-detail.js -> utils/rules.js ; services/catalog-enrichment.js -> utils/rules.js)",
      'economic-engine (prix produit, valorisation commerciale transport et audit price_history propriétaire)',
      'sourcing (persistence lifecycle sourcing_candidates et sourcing_candidate_events via sourcing-candidate-import-service ; catalog n execute plus de SQL direct sur ces tables)',
      'logistics (rails et eligibilite transport ; le catalog ne decide jamais le rail)',
      'shared-cart (ne pas reutiliser la modal catalogue pour la fiche snapshot)',
      'auth',
      'orders (actions panier depuis les surfaces produit boutique — preuve: b-catalog.js, render-product-card.js, b-modal-desktop-product.js, b-subcat.js, b-favs.js, b-modal-buybox-shared.js (+ tests) -> b-cart-core.js/b-cart.js, propriete orders-client canonicalFeature:orders)',
    ],
  },

  debt: {
    knownGaps: [
      {
        gap: 'contrat historique POST /api/admin/products/:id/publish : aucune route ne le sert. Depuis K-4, la publication se fait par la file d approbation.',
        risk: 'aucun — mecanisme remplace et couvert ; retirer toute reference historique restante lorsqu elle est rencontree.',
      },
      {
        gap: 'le contrat fournisseur V2 preserve media[], option_axes[] et sellable_units[] dans sourcing_candidates.normalized_source_contract, mais ces faits source ne sont pas encore promus vers les structures canoniques produit/media/options/SKU.',
        risk: 'GET /api/products/:id/detail v1 projette honnêtement les donnees canoniques actuelles products/product_variants/product_skus ; les roles source riches comme SCENE restent donc indisponibles tant que la promotion source vers catalogue n est pas explicite.',
      },
      {
        gap: 'le contrat detail v1 expose les rails deja commercialement exposes avec price_kmf reel (services/transport-pricing.js, quantity=1, poids/volume produit) depuis le chantier §9. eta_label reste null : aucune table ne relie un delai a SEA_STANDARD/AIR_EXPRESS (la table carriers existe mais c est un seed d exemple generique Dubai->Moroni, sans FK vers les rails, explicitement marque "a adapter avant la mise en prod").',
        risk: 'price_kmf est fiable (memes business_rules que orders/create.js) et retombe honnetement a null si le produit n a pas de weight_kg ou si le tarif est absent. eta_label reste interdit d affichage tant qu aucune decision business ne fournit un delai reel par rail ; interdiction de retomber sur Gratuit ou 3 a 5 semaines code en frontend.',
      },
      {
        gap: 'b-modal-core.js lance encore le fetch variantes legacy et modal-view-model.js reste necessaire pour des classes structurelles historiques.',
        risk: 'un guard de repaint transitoire protege PDC-4/PDC-5 ; PDC-6 doit supprimer le fetch legacy, l alias bootstrap mobile et les derniers owners structurels devenus inutiles.',
      },
    ],
  },

  authority: 'backend-core — normalized-product possede le contrat source versionne ; catalog possede le catalogue canonique et le contrat detail public ; toute modification modal catalogue suit DOCTRINE_PRODUCT_DETAIL_CONTRACT.md et docs/boutique/BOUTIQUE_MODAL_ARCHITECTURE.md',

  invariants: [
    'un produit publie a toujours passe product-publication-guard.js',
    'jamais de creation produit par formulaire vide : tout entre par un connecteur (le manuel EST un connecteur)',
    'la donnee source ne se perd jamais : raw_payload reste le brut integral et normalized_source_contract preserve separement le mapping V2 valide',
    'une structure riche connue ne doit pas etre aplatie puis reconstruite par heuristique ; une source pauvre reste pauvre honnêtement',
    'toute retouche manuelle est un override trace (catalog_field_overrides), jamais une edition de la fiche generee',
    'la boutique ne lit que les champs publies : les champs de cuisine source/content_source/normalized_source_contract lui sont invisibles',
    'une unite vendable = un SKU ; product_variants decrit les axes et ne porte pas la verite de stock cible',
    'GET /api/products/:id/detail retourne un contrat v1 valide par schema ; un produit legacy expose ses axes mais aucune fausse sellable_unit',
    'le contrat detail compose des faits et resultats proprietaires ; il ne recalcule ni pricing ni routing ni eligibilite rail',
    'delivery_options contient uniquement les rails deja commercialement exposes par logistics ; absence de prix ou ETA reste null tant qu aucun moteur proprietaire ne les fournit',
    'le frontend ne decide jamais d un rail ni d un delai universel de livraison',
    'mobile et desktop chargent le meme contrat detail et consomment le meme etat de selection SKU',
    'un seul owner derive disponibilite et media courants ; les renderers responsive ne font que composer',
    'b-modal-desktop-enhancers ne calcule ni prix ni stock ni livraison ni sous-total',
    'le prompt d enrichissement est du code : versionne dans le depot, chaque run trace, un echec IA ne bloque jamais un import',
    'la modal produit affiche le catalogue vivant et ne doit pas servir de fiche snapshot panier partage',
    'le parcours mobile Voir en grand appartient a b-modal-image-ux.js et modal-media.css',
    'aucune fiche candidate issue du pipeline ne passe lifecycle_status=active sans etre passee par la file d approbation, meme si needs_review est faux',
    'le pool fournisseur CJ de la Raffinerie ne dépasse jamais 1000 références propres ; son alimentation ne publie aucun produit automatiquement',
  ],
};
