/**
 * @feature       infrastructure
 * @type          transversal
 * @domain        infrastructure
 * @status        production
 * @owner         backend
 * @doctrine      docs/doctrine/FEATURE_DOCTRINE.md
 * @registry      scripts/feature-registry-check.js
 *
 * Manifeste niveau 0 (gouvernance fichiers) pour le domaine transversal
 * "infrastructure". Couvre les fichiers consommés par toutes les features
 * mais qui ne relèvent d'aucun domaine métier : middleware non-auth,
 * utilitaires partagés, validators, bootstrap applicatif.
 *
 * Créé le 2026-07-01 pour fermer le TROU 3 de l'audit gouvernance :
 * 19 fichiers étaient exemptés dans ORPHAN_IGNORE sans feature owner.
 */
'use strict';

module.exports = {

  name:     'infrastructure',
  type:     'transversal',
  domain:   'infrastructure',
  status:   'production',
  owner:    'backend',
  doctrine: 'docs/doctrine/FEATURE_DOCTRINE.md',

  service: "Infrastructure transversale consommée par toutes les features : middleware non-auth (error-handler, rate-limit, request-id, upload, validate), utilitaires partagés (logger, phone, rates, reference, rules), barrel de validation Joi, et bootstrap applicatif (Express, routes, crons, env, sécurité, migrations startup).",

  perimeter: {
    in:  ['middleware non-auth', 'utils transversaux', 'validators', 'bootstrap'],
    out: ['middleware auth (feature auth)', 'services métier', 'logique backend spécifique'],
  },

  files: {
    middleware: [
      'middleware/error-handler.js',
      'middleware/rate-limit.js',
      'middleware/request-id.js',
      'middleware/upload.js',
      'middleware/validate.js',
    ],
    utils: [
      'utils/logger.js',
      'utils/phone.js',
      'utils/rates.js',
      'utils/reference.js',
      'utils/rules.js',
    ],
    validators: [
      'validators/index.js',
    ],
    bootstrap: [
      'bootstrap/api-routes.js',
      'bootstrap/app.js',
      'bootstrap/crons.js',
      'bootstrap/env.js',
      'bootstrap/html-routes.js',
      'bootstrap/security.js',
      'bootstrap/server-lifecycle.js',
      'bootstrap/startup-migrations.js',
    ],
    migrations: [
      'migrations/016_add_missing_indexes.sql',
      'migrations/018_schema_reconciliation.sql',
      'migrations/069_analytical_indexes.sql',
      'migrations/AUD-10_rename_tracking_fix.sql',
      'migrations/deploy-all.sql',
    ],
    scripts: [
      'scripts/.boutique-360-baseline.json',
      'scripts/.dashboards-360-baseline.json',
      'scripts/.docs-history-lint-baseline.json',
      'scripts/.feature-schema-tests-baseline.json',
      'scripts/.meta-graph-baseline.json',
      'scripts/.security-360-baseline.json',
      'scripts/analyze-boutique-css.mjs',
      'scripts/apply-komerce-arch-headers-phase2.js',
      'scripts/apply-komerce-arch-headers-phase3.js',
      'scripts/apply-komerce-arch-headers.js',
      'scripts/apply-komerce-arch-total-coverage.js',
      'scripts/arch-db-check.js',
      'scripts/arch-debt-budget.json',
      'scripts/arch-doctrine-sanitize-check.js',
      'scripts/arch-header-sql-check.js',
      'scripts/arch-reconcile.js',
      'scripts/arch-schema-drift-check.js',
      'scripts/audit-backend-arch.js',
      'scripts/audit-komerce-arch-headers.js',
      'scripts/audit-sourcing.js',
      'scripts/boutique-ownership-check.js',
      'scripts/boutique-ownership-full-check.js',
      'scripts/check-boutique-doc-ack.js',
      'scripts/check-boutique.mjs',
      'scripts/check-schema-freshness.js',
      'scripts/ci-migrate.js',
      'scripts/ci-probe-token.js',
      'scripts/code-quality-gate.js',
      'scripts/contract-check.js',
      'scripts/contract-generate.js',
      'scripts/db-snapshot.js',
      'scripts/debt-audit.js',
      'scripts/docs-history-lint.js',
      'scripts/enrich-komerce-arch-db-fields.js',
      'scripts/f1-console-to-logger.js',
      'scripts/f1b-notification-logger-codemod.js',
      'scripts/feature-audit.js',
      'scripts/feature-classification-check.js',
      'scripts/feature-guard.js',
      'scripts/feature-memo.js',
      'scripts/feature-registry-check.js',
      'scripts/feature-schema-check.js',
      'scripts/fix-komerce-arch-links.js',
      'scripts/fix-schema.js',
      'scripts/gen-backend-arch-live.js',
      'scripts/gen-boutique-360.js',
      'scripts/gen-dashboards-360.js',
      'scripts/gen-meta-graph.js',
      'scripts/gen-security-360.js',
      'scripts/generate-komerce-arch-graph.js',
      'scripts/gov09-aud10-check.js',
      'scripts/h1a-wire-api-routes.js',
      'scripts/h1b-wire-html-routes.js',
      'scripts/h1c-wire-security.js',
      'scripts/h1d-wire-crons.js',
      'scripts/h1e-wire-env.js',
      'scripts/h1f-wire-startup-migrations.js',
      'scripts/h2-wire-server-lifecycle.js',
      'scripts/impact-check.js',
      'scripts/impact-config.json',
      'scripts/impact-suppressions.json',
      'scripts/komerce-db-reset.sh',
      'scripts/lib/arch-drift-core.js',
      'scripts/map-check.js',
      'scripts/migrate.js',
      'scripts/npm-audit-exceptions.json',
      'scripts/npm-audit-gate.js',
      'scripts/p0-runtime-check.js',
      'scripts/pr-governance-check.js',
      'scripts/predeploy-gate.js',
      'scripts/refine-komerce-arch-quality.js',
      'scripts/refresh-schema.js',
      'scripts/refresh-schema.sh',
      'scripts/reset-admin.js',
      'scripts/run-migrations.js',
      'scripts/run-security-360.js',
      'scripts/seed.js',
      'scripts/setup-hooks.sh',
      'scripts/test-settings-api.sh',
      'scripts/test_e2e_full.sh',
      'scripts/touched-files-feature-gate.js',
      'scripts/touched-tests-gate.js',
      'scripts/validate-required-env.js',
      'audit-backend-arch.js',
    ],
    docs: [
      'docs/AUDIT_CONFORMITE_PRE_GOLIVE_2026-06-08.md',
      'docs/BOUTIQUE_360.json',
      'docs/BOUTIQUE_360.md',
      'docs/BRAND_TRUTH_KOMERCE.md',
      'docs/CABLAGE.md',
      'docs/CARTE_FIRST_INDEX.md',
      'docs/CARTOGRAPHY_360.md',
      'docs/CONTRACTS.md',
      'docs/D1_CARTOGRAPHIE_PROVIDER_NOTIFICATIONS.md',
      'docs/DASHBOARDS_360.json',
      'docs/DASHBOARDS_360.md',
      'docs/DECOUPAGE.md',
      'docs/FIX_ERROR_HANDLER_22P02.md',
      'docs/KNOWN_FAILING_TESTS.md',
      'docs/KOMERCE_ARCHITECTURE_HEADERS.md',
      'docs/KOMERCE_ARCHITECTURE_MAP.md',
      'docs/KOMERCE_ARCH_CARTOGRAPHY_STATUS.md',
      'docs/KOMERCE_ARCH_GRAPH_DOCTRINE.md',
      'docs/KOMERCE_ARCH_HEADER_AUDIT.md',
      'docs/KOMERCE_ARCH_HEADER_GRAPH.md',
      'docs/KOMERCE_DB_SCHEMA_DOCTRINE.md',
      'docs/KOMERCE_DB_TOUCHPOINTS_MAP.md',
      'docs/META_GRAPH.json',
      'docs/META_GRAPH.md',
      'docs/P4_1_CALIBRAGE_RUN2.md',
      'docs/P4_1_PREMIER_RUN.md',
      'docs/PAYPAL_IMPLEMENTATION_GUIDE.md',
      'docs/README.md',
      'docs/RECONCILIATION_2026-06-16.md',
      'docs/ROLLBACK_PLAN.md',
      'docs/RUNBOOK_DEBLOCAGE_HOOKS.md',
      'docs/SCHEMA.md',
      'docs/SECURITY_360.json',
      'docs/SECURITY_360.md',
      'docs/SECURITY_360_METHODE.md',
      'docs/SIGNOFF_REVERIF.md',
      'docs/SOURCING_ENGINE.md',
      'docs/SUPPLIERS_CONNECTORS.md',
      'docs/ZONE_IMPACT.md',
      'docs/_agent/README.md',
      'docs/_agent/session_history/2026-04-07_bootstrap.md',
      'docs/_agent/state.md',
      'docs/_agent/workspace/.gitkeep',
      'docs/_archive/AGENT_CONFIG.md',
      'docs/_archive/AGENT_SUBAGENTS.md',
      'docs/_archive/AUDIT_BACKEND_FINDINGS.md',
      'docs/_archive/AUDIT_CONFORMITE_GOUVERNANCE.md',
      'docs/_archive/AUDIT_KOMERCE_FINAL.md',
      'docs/_archive/AUDIT_REPORT.md',
      'docs/_archive/CHANGELOG-P0.md',
      'docs/_archive/CHANGES_PHASE2_MIGRATION.md',
      'docs/_archive/GOVERNANCE.md',
      'docs/_archive/GOVERNANCE_BOOTSTRAP.md',
      'docs/_archive/IMPACT_SYSTEM.md',
      'docs/_archive/INSTRUCTIONS.md',
      'docs/_archive/PATCH_BOUTIQUE_ARCHITECTURE.md',
      'docs/_archive/PATCH_BOUTIQUE_MODAL_ARCHITECTURE.md',
      'docs/_archive/PHASE-1-audit-coherence.md',
      'docs/_archive/PROMPTS_KIT.md',
      'docs/_archive/RAPPORT_LOTS_CSS_1-4.md',
      'docs/_archive/README.md',
      'docs/_archive/READY_TO_ORDER_ROUTE_PATCH.md',
      'docs/_archive/REPRISE_SESSION.md',
      'docs/_archive/ROADMAP_KOMERCE.md',
      'docs/_archive/ROADMAP_KOMERCE_PROD_FINALE.md',
      'docs/_archive/SCHEMA_GAP_KOMERCE.md',
      'docs/_archive/VALIDATION_GUIDE.md',
      'docs/_archive/komerce-point6-gouvernance-operationnelle.md',
      'docs/_logs/2026-04-07_09-53_sync.md',
      'docs/_logs/2026-04-07_09-54_sync.md',
      'docs/_logs/2026-04-07_phase1_parcels.md',
      'docs/_logs/2026-04-07_phase2_parcels.md',
      'docs/_logs/2026-04-07_phase4_cleanup.md',
      'docs/_logs/PHASE2_PARCEL_CHANGELOG.md',
      'docs/_logs/README.md',
      'docs/_pending/README.md',
      'docs/_work/.gitkeep',
      'docs/_work/2026-04-07_phase2_parcels_analysis.md',
      'docs/_work/AUDIT_CODE_VS_TRUTH_2025-04-07.md',
      'docs/_work/BOUTIQUE_LOT1_TOKENS_CASSES_AUDIT.md',
      'docs/_work/PARTS_MODULE_ANALYSIS.md',
      'docs/_work/README.md',
      'docs/_work/SOURCING_DB_AUDIT.md',
      'docs/_work/audit-code-vs-truth-2026-04-07.md',
      'docs/adr/ADR-001-customs-shipments.md',
      'docs/adr/ADR-002-sales-analytics-v2.md',
      'docs/adr/ADR-003-accounting-v2.md',
      'docs/adr/ADR-004-customs-rate-coherence.md',
      'docs/adr/ADR-005-suppliers-unifies.md',
      'docs/adr/ADR-006-clients-view.md',
      'docs/adr/ADR-007-finance-bo-hygiene.md',
      'docs/adr/ADR-008-pilotage-split-and-sante.md',
      'docs/adr/ADR-009-source-verite-unifiee.md',
      'docs/adr/ADR-010-pricing-reads-db.md',
      'docs/adr/ADR-011-pricing-extensible-3-niveaux.md',
      'docs/adr/ADR-012-migration-scans-scan-events.md',
      'docs/audit/AUDIT_BUGS.md',
      'docs/audit/AUDIT_CODE_INTEGRITY.md',
      'docs/audit/AUDIT_DELTA_BACKEND_2026-06-14.md',
      'docs/audit/AUDIT_KOMERCE_3D.md',
      'docs/audit/AUDIT_PREGOLIVE_2026-06-22.md',
      'docs/audit/FRONTEND_AUDIT.md',
      'docs/audit/GOV-02_UNPROTECTED_CLASSIFICATION.md',
      'docs/audit/LOT7_FINAL_PARITY.md',
      'docs/audit/PROMPT_SONNET_DEPLOY_ORCHESTRATION_KOMERCE.md',
      'docs/audit/PROMPT_SONNET_LOT387_KOMERCE.md',
      'docs/audit/PROMPT_SONNET_NOTIFICATIONS_PROVIDER_KOMERCE.md',
      'docs/audit/PROMPT_SONNET_OBSERVABILITY_LOGS_KOMERCE.md',
      'docs/audit/PROMPT_SONNET_SECURITY_GOLIVE_KOMERCE.md',
      'docs/audit/REFACTO_ROUTES_VERIFICATION_2026-06-14.md',
      'docs/audit/SECURITY_CHECKLIST.md',
      'docs/audit/batch_2.md',
      'docs/audit/batch_3.md',
      'docs/audit/batch_5.md',
      'docs/audit/batch_6.md',
      'docs/audit/db_audit.md',
      'docs/audit/findings_updated.ndjson',
      'docs/audit/middleware_audit.md',
      'docs/audit/utils_audit.md',
      'docs/backend/ARCHI_DECOUPAGE_MODULAIRE.md',
      'docs/backend/BACKEND_AUDIT.md',
      'docs/backend/BACKEND_AUDIT_CORRECTIONS.md',
      'docs/backend/BACKEND_AUDIT_SESSIONS_PLAN.md',
      'docs/backend/BACKEND_GOLIVE_ROADMAP.md',
      'docs/backend/COMPATIBILITE_SOURCING_VAGUE_3.md',
      'docs/backend/COUTURE_SIMPLIFICATION.md',
      'docs/backend/PANIER_COLLECTIF_BACKEND_DELTA.md',
      'docs/backend/ROUTES_REFACTO_ANALYSIS_2026-06-14.md',
      'docs/backend/SECURITY-MODEL.md',
      'docs/boutique/BOUTIQUE_ARCHITECTURE.md',
      'docs/boutique/BOUTIQUE_CATEGORY_NAVIGATION_REDESIGN.md',
      'docs/boutique/BOUTIQUE_COMPONENT_OWNERSHIP.md',
      'docs/boutique/BOUTIQUE_CSS_PIPELINE.md',
      'docs/boutique/BOUTIQUE_DESKTOP_REDESIGN_BRIEF.md',
      'docs/boutique/BOUTIQUE_DOCS_INDEX.md',
      'docs/boutique/BOUTIQUE_MODAL_ARCHITECTURE.md',
      'docs/boutique/BOUTIQUE_PRODUCT_DISPLAY_CONTRACT.md',
      'docs/boutique/BOUTIQUE_WOW_LAYER_ARCHITECTURE.md',
      'docs/boutique/HOTFIX_V3_README.md',
      'docs/boutique/HOTFIX_V4_README.md',
      'docs/boutique/MOBILE_BOUTIQUE_AUDIT.md',
      'docs/boutique/MOBILE_BOUTIQUE_FIXES.md',
      'docs/boutique/README.md',
      'docs/boutique/ROADMAP_MODAL_TEMU.md',
      'docs/boutique/komerce-categories-design.md',
      'docs/chantier/ADMIN_AUTH_AUDIT_D1.md',
      'docs/chantier/ARCH_SCAN_2026-05-19.md',
      'docs/chantier/AUDIT_MIGRATIONS_060_061.md',
      'docs/chantier/AUTH_GUEST_AUDIT_D3.md',
      'docs/chantier/BACKEND_FIXES_REGISTER.md',
      'docs/chantier/BACKUP_DB_AUDIT_F6.md',
      'docs/chantier/BLINDAGE_BASE0_2026-06-16.md',
      'docs/chantier/CARTOGRAPHY_360.md',
      'docs/chantier/CHECKPOINT_2026-05-21_H1_COMPLETE.md',
      'docs/chantier/CLOTURE_CYCLE_CRITIQUE_BACKEND.md',
      'docs/chantier/CORS_AUDIT_D7.md',
      'docs/chantier/CORS_HELMET_AUDIT_D7_D8.md',
      'docs/chantier/ENV_AUDIT_D5.md',
      'docs/chantier/F1B_NOTIFICATION_LOGGER_CODEMOD.md',
      'docs/chantier/FLOW_AUDIT_CANCEL_G4.md',
      'docs/chantier/FLOW_AUDIT_CASH_G1.md',
      'docs/chantier/FLOW_AUDIT_COLLECTIVE_G3.md',
      'docs/chantier/FLOW_AUDIT_SOURCING_G5.md',
      'docs/chantier/FLOW_AUDIT_STRIPE_G2.md',
      'docs/chantier/GATES_AUDIT.md',
      'docs/chantier/GOVERNANCE_STATUS.md',
      'docs/chantier/H1A_SERVER_WIRING_CODEMOD.md',
      'docs/chantier/H1B_HTML_ROUTES_CODEMOD.md',
      'docs/chantier/H1C_SECURITY_CODEMOD.md',
      'docs/chantier/H1D_CRONS_CODEMOD.md',
      'docs/chantier/HELMET_AUDIT_D8.md',
      'docs/chantier/I_SWEEP_1_PICKUP_CASH_PATCH.md',
      'docs/chantier/I_SWEEP_PLAN.md',
      'docs/chantier/KOMERCE_CORRECTIONS_360_CONSOLIDE.md',
      'docs/chantier/KOMERCE_HARMONISATION_ARCHI.md',
      'docs/chantier/LOGGER_GUIDELINES.md',
      'docs/chantier/LOT_B_C_REFACTO.md',
      'docs/chantier/MIGRATIONS_FOLDERS_A5.md',
      'docs/chantier/P0_RUNTIME_CHECK.md',
      'docs/chantier/PLAN_H1F_STARTUP_MIGRATIONS.md',
      'docs/chantier/PLAN_H1_REFACTO_SERVER.md',
      'docs/chantier/PLAN_POLISSAGE_GOUVERNANCE.md',
      'docs/chantier/PROMPTS_KIT_POST_CRITIQUE.md',
      'docs/chantier/QR_PICKUP_SECRET_AUDIT_D4.md',
      'docs/chantier/RATE_LIMIT_AUDIT_D6.md',
      'docs/chantier/README.md',
      'docs/chantier/STATUS.md',
      'docs/chantier/STATUS_SONNET_PANIER_V42.md',
      'docs/chantier/STRIPE_WEBHOOK_AUDIT_D2.md',
      'docs/chantier/VALIDATION_STAGING_2026-05-19.md',
      'docs/chantier/ZONE_IMPACT.md',
      'docs/chantier/komerce_backlog.ndjson',
      'docs/chantier/lot7_final_status.ndjson',
      'docs/contract/DEBT.md',
      'docs/contract/openapi.json',
      'docs/db/railway-live-schema.sql',
      'docs/design/DASHBOARD_REDESIGN.md',
      'docs/design/TOUR-DE-CONTROLE-DASHBOARDS.md',
      'docs/design/analyse-dashboard-pilotage.md',
      'docs/doctrine/APP_FEATURE_REGISTRY.md',
      'docs/doctrine/AUDIT_FEATURE_DOCTRINE.md',
      'docs/doctrine/BACKEND_FEATURE_REGISTRY.md',
      'docs/doctrine/BOUTIQUE_PERSONNALISATION_NAVIGATION.md',
      'docs/doctrine/CERTIFICATION_DOCTRINE_FEATURE.md',
      'docs/doctrine/DECISIONS_ARCHI_GROUPE_C.md',
      'docs/doctrine/DOCTRINE_ALLOCATION_COUTS.md',
      'docs/doctrine/DOCTRINE_DOCUMENTS_TRANSACTIONNELS_KOMERCE.md',
      'docs/doctrine/DOCTRINE_ECONOMIQUE_KOMERCE.md',
      'docs/doctrine/DOCTRINE_IDENTITE_LEGERE_KOMERCE.md',
      'docs/doctrine/DOCTRINE_LEVIERS_MARGE.md',
      'docs/doctrine/DOCTRINE_MOTEUR_ECONOMIQUE_STRATEGIE.md',
      'docs/doctrine/DOCTRINE_PANIER_COLLECTIF.md',
      'docs/doctrine/DOCTRINE_PANIER_PARTAGE.md',
      'docs/doctrine/DOCTRINE_PANIER_PARTAGE_SURCOUVERTURE.md',
      'docs/doctrine/DOUANE_DECLARATION_PIVOT.md',
      'docs/doctrine/FEATURE_DOCTRINE.md',
      'docs/doctrine/FEATURE_SLICE_DOCTRINE.md',
      'docs/doctrine/MOTEUR_ECONOMIQUE_ALLOCATION.md',
      'docs/doctrine/PANIER_PARTAGE_BOUTIQUE_FIRST.md',
      'docs/doctrine/QUALITY_PYRAMID_DOCTRINE.md',
      'docs/fix-gate-prefix.patch.md',
      'docs/implementation/PANIER_PARTAGE_BOUTIQUE_FIRST.md',
      'docs/komerce-arch-header-audit.json',
      'docs/komerce-arch-header-graph.json',
      'docs/komerce-architecture-map.json',
      'docs/ops/DEPLOYMENT.md',
      'docs/ops/DEPLOY_GUIDE_V2.md',
      'docs/ops/PAYPAL_POSITIONNEMENT.md',
      'docs/ops/PLAN_LANCEMENT_OPERATIONNEL.md',
      'docs/ops/PLAN_LOGISTIQUE_V2.md',
      'docs/ops/SYNOPTIQUE_KOMERCE.md',
      'docs/ops/komerce_architecture.mmd',
      'docs/prompts/PROMPT_DASHBOARD_ECONOMIQUE_BOITES_FLECHES.md',
      'docs/specs/SPEC-ORDER-PARCEL-LIFECYCLE.md',
      'docs/specs/SPEC_BACKEND_VAGUE_3_VARIANTES_V2.md',
      'docs/specs/SPEC_KEYSTONE_DOUANE.md',
      'docs/specs/SPEC_SUR_MESURE_PAGE.md',
      'docs/specs/TEST_CHECKLIST_KOMERCE.md',
      'docs/specs/collective-workspaces-v1.md',
      'docs/specs/event-flow-v2.md',
      'docs/vision/BRAND_TRUTH_v8.md',
      'docs/vision/ROADMAP_PILOTE_KOMERCE.md',
      'docs/vision/VISION_MARCHE_KOMERCE.md',
      'AGENTS.md',
      'AUDIT_FEATURE_DOCTRINE.md',
      'CONTRIBUTING.md',
      'CORRECTIONS_GOUVERNANCE_2026-07-01.md',
      'PROCEDURE.md',
      'PROMPT_AUDIT_PREGOLIVE.md',
      'README.md',
    ],
    ci: [
      '.github/CODEOWNERS',
      '.github/copilot-instructions.md',
      '.github/pull_request_template.md',
      '.github/workflows/apply-komerce-arch-headers-once.yml',
      '.github/workflows/apply-komerce-arch-headers-phase2-once.yml',
      '.github/workflows/apply-komerce-arch-headers-phase3-once.yml',
      '.github/workflows/apply-komerce-arch-headers.yml',
      '.github/workflows/apply-komerce-arch-total-coverage-once.yml',
      '.github/workflows/audit-komerce-arch-headers-once.yml',
      '.github/workflows/carte-first.yml',
      '.github/workflows/carto-guard.yml',
      '.github/workflows/ci.yml',
      '.github/workflows/contract-conformance.yml',
      '.github/workflows/contract.yml',
      '.github/workflows/docs-guard.yml',
      '.github/workflows/enrich-komerce-arch-db-fields-once.yml',
      '.github/workflows/fix-komerce-arch-links-once.yml',
      '.github/workflows/generate-komerce-arch-graph-once.yml',
      '.github/workflows/generate-komerce-arch-graph.yml',
      '.github/workflows/governance.yml',
      '.github/workflows/impact-check.yml',
      '.github/workflows/pr-governance.yml',
      '.github/workflows/refine-komerce-arch-quality-once.yml',
      '.github/workflows/refine-komerce-arch-quality-v2-once.yml',
      '.github/workflows/schema-refresh.yml',
    ],
    assets: [
      'public/images/Komerce_Hero_Desktop.png',
      'public/images/Komerce_Kero_Desktop_2.png',
      'public/images/Logo_Komerce.png',
      'public/images/Logo_Komerce@2x.png',
      'public/images/Logo_Komerce_white.png',
      'public/images/apple-touch-icon.png',
      'public/images/avatar_panier.png',
      'public/images/avatar_seule.png',
      'public/images/categories/cat-beaute.jpg',
      'public/images/categories/cat-beaute.svg',
      'public/images/categories/cat-couture.jpg',
      'public/images/categories/cat-couture.svg',
      'public/images/categories/cat-enfant.jpg',
      'public/images/categories/cat-enfant.svg',
      'public/images/categories/cat-mode.jpg',
      'public/images/categories/cat-mode.svg',
      'public/images/categories/cat-tech.jpg',
      'public/images/categories/cat-tech.svg',
      'public/images/categories/cat-tout.jpg',
      'public/images/categories/cat-tout.svg',
      'public/images/favicon-16.png',
      'public/images/favicon-192.png',
      'public/images/favicon-32.png',
      'public/images/favicon.ico',
      'public/images/icon-192.png',
      'public/images/icon-512.png',
      'public/images/komerce_hero_desktop_1600x320.webp',
      'public/images/komerce_hero_desktop_1600x386.webp',
      'public/images/komerce_hero_desktop_1600x525.webp',
      'public/images/komerce_hero_final_1080x260.webp',
      'public/images/komerce_hero_final_1080x310.webp',
      'public/images/komerce_hero_mobile_1080x220.webp',
      'public/images/komerce_hero_mobile_1080x260.webp',
      'public/images/panier_africain.png',
      'public/images/panier_africain_sm.png',
      'public/images/panier_tresse.png',
      'public/images/panier_tresse_vert.png',
    ],
    db: [
      'db/migrations/004_fix_order_status_enum.sql',
      'db/migrations/005_add_in_transit_status.sql',
      'db/migrations/006_dashboard_columns.sql',
      'db/migrations/007_business_rules.sql',
      'db/migrations/008_pricing_rules.sql',
      'db/migrations/009_partial_shipping.sql',
      'db/migrations/010_parcels_foundation.sql',
      'db/migrations/011_parcels_dual_write.sql',
      'db/migrations/012_parcels_trigger_migration.sql',
      'db/migrations/013_legacy_cleanup.sql',
      'db/migrations/014_transaction_documents.sql',
      'db/migrations/083_transaction_documents.sql',
      'db/schema.sql',
      'db/schema_extension.sql',
      'db/seed-products-v2.json',
      'db/seed.sql',
    ],
    config: [
      'db.js',
      'server.js',
      '.cursorrules',
      '.env.example',
      '.gitattributes',
      '.gitignore',
      '.nvmrc',
      'jest.config.js',
      'package-lock.json',
      'package.json',
      'railway.json',
      'railway.toml',
      'RECONCILIATION_PROD.sql',
    ],
    tests: [
      'tests/integration/groupe-paiement.manual.js',
      'tests/integration/test-harness/mock-db.js',
      'tests/test-benchmarks.js',
      'tests/test-chain.js',
      'tests/test-flow-contract.js',
      'tests/unit/error-handler-fallback.test.js',
      'tests/unit/error-handler.test.js',
      'tests/unit/logger.test.js',
      'tests/unit/order-parcel-link-rules.test.js',
      'tests/unit/phone.test.js',
      'tests/unit/rate-limit.test.js',
      'tests/unit/rates.test.js',
      'tests/unit/reference.test.js',
      'tests/unit/request-id.test.js',
      'tests/unit/rules-engine.test.js',
      'tests/unit/upload.test.js',
    ],
  },

  contract: {
    exposes: [
      'middleware/error-handler.js — gestion centralisée des erreurs Express',
      'middleware/rate-limit.js — rate limiting par IP/route',
      'middleware/request-id.js — injection X-Request-Id',
      'middleware/upload.js — multer file upload',
      'middleware/validate.js — validation Joi des requêtes',
      'utils/logger.js — wrapper pino structuré',
      'utils/phone.js — normalisation numéros téléphone Comores',
      'utils/rates.js — taux de change KMF/EUR',
      'utils/reference.js — génération de références commande/colis',
      'utils/rules.js — moteur de règles métier centralisé',
      'validators/index.js — barrel des schémas Joi',
      'bootstrap/* — démarrage Express, routage, crons, migrations',
    ],
    consumes: [
      'auth — bootstrap/api-routes.js monte les routes auth',
      'catalog — bootstrap/api-routes.js monte les routes catalog',
      'customs — bootstrap/api-routes.js monte les routes customs',
      'dashboard — bootstrap/api-routes.js monte les routes dashboard',
      'economic-engine — bootstrap/api-routes.js monte les routes economic-engine',
      'inventory — bootstrap/api-routes.js monte les routes inventory',
      'logistics — bootstrap/api-routes.js monte les routes logistics',
      'notification — bootstrap/api-routes.js monte les routes notification',
      'operations — bootstrap/api-routes.js monte les routes operations',
      'orders — bootstrap/api-routes.js monte les routes orders',
      'payment — bootstrap/api-routes.js monte les routes payment',
      'recommendations — bootstrap/api-routes.js monte les routes recommendations',
      'shared-cart — bootstrap/api-routes.js monte les routes shared-cart',
      'wallet — bootstrap/api-routes.js monte les routes wallet',
    ],
  },

  authority: 'backend — ces fichiers sont consommés par toutes les features. Tout changement ici a un impact potentiel global.',

  invariants: [
    'tout fichier middleware/ non-auth doit être listé ici',
    'tout fichier utils/ à @domain infrastructure doit être listé ici',
    'tout fichier bootstrap/ doit être listé ici',
    'validators/index.js est le barrel unique de validation',
  ],

};
