/**
 * @feature       purchasing
 * @type          feature
 * @domain        purchasing
 * @status        production
 * @owner         backend-core
 * @since         2025-09
 * @doctrine      docs/doctrine/FEATURE_DOCTRINE.md
 * @registry      docs/doctrine/APP_FEATURE_REGISTRY.md
 */
'use strict';

module.exports = {

  name:     'purchasing',
  type:     'feature',
  domain:   'purchasing',
  status:   'production',
  owner:    'backend-core',
  since:    '2025-09',
  doctrine: 'docs/doctrine/FEATURE_DOCTRINE.md',

  service: 'Transformer un besoin d\'approvisionnement issu d\'une commande en engagement fournisseur traçable (bon de commande), puis constater sa réception.',

  perimeter: {
    in: [
      'préflight Allegro Sandbox : identité exacte et stock/prix live ; fulfillment manuel prêt sans prétendre à un buyer placeOrder API',
      'réconciliation d\'achat manuel Allegro Sandbox : le proof runner peut découvrir de façon bornée la commande vendeur READY_FOR_PROCESSING postérieure à la PO, exige un match unique sur offer_id/SOI + quantité + monnaie native, puis confirme uniquement ce checkoutForm exact',
      'déclenchement automatique d\'un bon de commande (purchase_order) quand une commande client nécessite un réassort fournisseur',
      'notification/confirmation du fournisseur (manuel ou WhatsApp) et suivi du statut du bon de commande',
      'réception (partielle ou totale) d\'un bon de commande, et rattachement au flux logistique',
      'synchronisation d\'annulation : pending/notified suivent l\'annulation de la commande ; les POs engagées déclenchent une alerte sans forçage',
      'réparation/rattrapage des commandes marquées "ordered" sans (ou avec) bon de commande cohérent (outils admin de correction)',
      'gestion des fournisseurs et de leur mapping produit (routes/purchasing.js /suppliers/*)',
      'administration transverse des bons de commande, historiquement exposée depuis le dashboard ' +
        '(services/purchasing-admin-service.js — retaggé @domain purchasing au Lot O2, ' +
        'écrit orders/product_suppliers/purchase_orders/suppliers)',
      'Supplier Order Identity universelle : une unité vendable doit se résoudre sans ambiguïté vers exactement une unité commandable fournisseur avant tout engagement',
      'Procurement Route canonique : l\'achat fournisseur est routé vers un Procurement Hub explicite avant la jambe logistique Market ; aucune destination client/Market brute ne peut être assimilée à la destination fournisseur',
      'préflight fournisseur AliExpress avant engagement : réconciliation SKU, stock/prix live, fret Supplier → Procurement Hub et construction fail-closed du payload d\'achat sans exécution automatique',
      'Supplier Fulfillment Readiness dynamique : évaluer SKU × quantité × Procurement Route à partir de l\'identité fournisseur persistée, du refresh live et du fret, sans mutation fournisseur',
      'Supplier Fulfillment Adapter Contract universel : chaque fournisseur déclare son provider et renvoie exclusivement les verdicts canoniques Purchasing, tandis que son payload natif reste opaque au coeur Komerce',
      'workflow capability-driven : AUTO_API, MANUAL_EXTERNAL, READINESS_ONLY ou BLOCKED sont dérivés des capacités réellement prouvées ; aucune étape humaine n est inventée comme fallback générique',
      'Shipping Capability Adapter Contract : les faits de livraison natifs d\'un provider sont traduits en capacité canonique sans fuite de champs provider ni défaut implicite sur les faits inconnus',
      'Purchase Order exacte : pour une ligne vendue avec sku_id, la PO conserve order_item_id, product_sku_id et la Supplier Order Identity snapshotée ; un mapping produit-level ne peut pas remplacer la variante vendue',
      'engagement d\'une PO regroupée (PR 5) : soumission par groupe supplier_unit_ref, confirmation par PO ligne par ligne avec reliquat en ligne ouverte, écart à la réception (solde d\'une ligne confirmée), création manuelle d\'une ligne ouverte ; contrat adaptateur items[] (buildOrderPayload / reconcile)',
      'complétude d\'achat après réception Hub (PR 7) : purchasing-completion-service passe une PO regroupée en hub_received quand toutes ses lignes non annulées sont reçues et une commande ordered en preparation (puis SCAN 3) quand chaque item non LOCAL_STOCK est couvert ET reçu, appelée après COMMIT par hub-operations, jamais bloquante (alerte purchasing_completion_failed) ; deleteSupplier annule les lignes ouvertes et refuse les PO en brouillon ; signaux lus sur les lignes',
      'Supplier money canonique : pour une ligne SKU/SOI exacte, la PO snapshotte supplier_unit_price + supplier_currency depuis la Canonical Unit ; aucun prix natif non-AED ne peut être écrit dans unit_price_aed',
      'Golden E2E achat provider + full-chain : chaque capacité fournisseur est qualifiée P0→P4 séparément, puis la chaîne B2C paid → purchase_line/PO → provider evidence → coût B2B → compta B2B/B2C scopée → rapprochement est prouvée sans gate de confirmation humaine Komerce',
    ],
    out: [
      'cycle de vie de la commande cliente elle-même — orders reste seul propriétaire de order-status-machine.js ' +
        '(feature orders, scindée au Lot O1.4)',
      'confirmation de paiement client (order-payment-confirmation.js, reste dans orders)',
      'mouvement physique du colis une fois reçu (feature logistics, lecture seule sur purchase_orders/product_suppliers)',
      'entrée catalogue / import fournisseur en amont (feature catalog — sourcing/catalog-import, hors périmètre purchasing)',
    ],
  },

  docs: [
    'docs/doctrine/DOCTRINE_SUPPLIER_ORDER_IDENTITY.md',
    'docs/doctrine/DOCTRINE_PROCUREMENT_FULFILLMENT.md',
    'docs/doctrine/DOCTRINE_CANONICAL_UNIT_PURCHASING.md',
    'docs/doctrine/DOCTRINE_PURCHASING_PROVIDER_GOLDEN_E2E.md',
    'docs/doctrine/DOCTRINE_PURCHASING_CAPABILITY_DRIVEN_EXECUTION.md',
    'docs/allegro-sandbox.md',
    'docs/allegro-shipping-capability-p2.md',
    'docs/external-providers/suppliers/CJ_PURCHASING_CONTRACT.md',
  ],

  files: {
    services: [
      'services/suppliers/allegro-fulfillment-adapter.js',
      'services/suppliers/allegro-purchase-reconciliation.js',
      'services/suppliers/allegro-shipping-capability-adapter.js',
      'services/suppliers/shipping-capability-contract.js',
      'services/purchasing-trigger-service.js',
      'services/suppliers/execution-adapter-registry.js',
      'services/purchasing-canonical-money.js',
      'services/suppliers/purchasing-validators.js',
      'services/suppliers/aliexpress-purchase-preflight.js',
      'services/suppliers/supplier-fulfillment-readiness.js',
      'services/suppliers/canonical-unit-purchasing-gate.js',
      'services/suppliers/procurement-execution-boundary.js',
      'services/suppliers/purchasing-capability-execution-plan.js',
      'services/suppliers/purchase-order-confirmation-boundary.js',
      'services/suppliers/canonical-unit-cutover-comparison.js',
      'services/suppliers/aliexpress-fulfillment-adapter.js',
      'services/suppliers/cj-purchasing-contract.js',
      'services/suppliers/cj-fulfillment-adapter.js',
      'services/purchasing-receive-service.js',
      'services/purchasing-cancel-service.js',
      'services/receive-purchase-order.js',
      'services/repair-ordered-purchasing.js',
      'services/repair-ordered-without-purchase-orders.js',
      'services/purchasing-admin-service.js',
      'services/purchase-line-snapshot.js',
      'services/purchasing-grouped-service.js',
      'services/purchasing-engagement-service.js',
      'services/purchasing-completion-service.js',
    ],
    routes: [
      'routes/purchasing.js',
    ],
    migrations: [
      'migrations/274_supplier_platform_cj.sql',
      'migrations/225_purchase_orders_exact_supplier_identity.sql',
      'migrations/239_purchase_orders_canonical_supplier_money.sql',
      'migrations/263_purchase_lines_foundation.sql',
      'migrations/264_purchase_line_progress_view.sql',
      'migrations/266_purchase_orders_grouped_form.sql',
    ],
    scripts: [
      'scripts/purchase-lines-parity-check.js',
      'scripts/allegro-sandbox-purchase-proof.js',
      'scripts/allegro-shipping-capability-proof.js',
      'scripts/aliexpress-readiness-golden-proof.js',
      'scripts/cj-p1-create-readback-proof.js',
    ],
    tests: [
      'tests/unit/provider-authority.test.js',
      'tests/unit/purchase-line-snapshot.test.js',
      'tests/unit/purchase-lines-parity-check.test.js',
      'tests/integration/purchase-lines-postgres.test.js',
      'tests/integration/purchase-line-progress-postgres.test.js',
      'tests/integration/purchase-lines-grouped-postgres.test.js',
      'tests/integration/purchase-lines-engagement-postgres.test.js',
      'tests/unit/purchasing-engagement-service.test.js',
      'tests/unit/purchasing-completion-service.test.js',
      'tests/unit/hub-operations-grouped-completion.test.js',
      'tests/unit/allegro-golden-native-money-grouped-proof.test.js',
      'tests/e2e-api/purchasing.grouped-flow.e2e.test.js',
      'tests/unit/allegro-fulfillment-adapter.test.js',
      'tests/unit/shipping-capability-contract.test.js',
      'tests/unit/allegro-purchase-reconciliation.test.js',
      'tests/unit/allegro-seller-order-read.test.js',
      'tests/unit/allegro-sandbox-purchase-proof.test.js',
      'tests/unit/allegro-shipping-capability-adapter.test.js',
      'tests/unit/allegro-shipping-capability-proof.test.js',
      'tests/e2e-api/purchasing.no-duplicate-po.e2e.test.js',
      'tests/integration/purchasing-exact-sku-po.test.js',
      'tests/integration/purchasing-wa-url-w3-1.test.js',
      'tests/unit/purchasing.test.js',
      'tests/unit/purchasing-receive-service.test.js',
      'tests/unit/purchasing-cancel-service.test.js',
      'tests/unit/purchasing-route.test.js',
      'tests/unit/purchasing-trigger-service.test.js',
      'tests/unit/purchasing-adapter-resolution.test.js',
      'tests/unit/purchasing-trigger-exact-sku.test.js',
      'tests/unit/purchasing-canonical-money.test.js',
      'tests/unit/canonical-unit-purchasing-gate.test.js',
      'tests/unit/procurement-execution-boundary.test.js',
      'tests/unit/purchasing-capability-execution-plan.test.js',
      'tests/unit/purchase-order-confirmation-boundary.test.js',
      'tests/unit/purchasing-readiness-vocabulary-mapping.test.js',
      'tests/unit/canonical-unit-cutover-comparison.test.js',
      'tests/unit/aliexpress-purchase-preflight.test.js',
      'tests/unit/aliexpress-readiness-golden-proof.test.js',
      'tests/unit/cj-purchasing-contract.test.js',
      'tests/unit/cj-fulfillment-adapter.test.js',
      'tests/unit/cj-p1-create-readback-proof.test.js',
      'tests/unit/supplier-fulfillment-readiness.test.js',
      'tests/unit/receive-purchase-order.test.js',
      'tests/unit/repair-ordered-purchasing.test.js',
      'tests/unit/repair-ordered-without-purchase-orders.test.js',
      'tests/unit/purchasing-admin-service.test.js',
    ],
  },

  db: {
    tables: [
      'order_items: R',
      'orders: R',
      'product_skus: R',
      'product_suppliers: RW',
      'products: R',
      'purchase_orders: RW!',
      'relais: R',
      'suppliers: RW',
    ],
  },

  security: {
    status: 'CONFIRMED_PROTECTED',
    authedRoutesDetected: 20,
    totalRoutes: 20,
    note: '20/20 routes protégées (guard admin appliqué sur chaque route de routes/purchasing.js — GET/POST/DELETE confondus, y compris le référentiel fournisseur).',
  },
  contract: {
    exposes: [
      'GET /api/purchasing',
      'GET /api/purchasing/suppliers',
      'POST /api/purchasing/suppliers',
      'POST /api/purchasing/suppliers/:id/map',
      'DELETE /api/purchasing/suppliers/:id',
      'GET /api/purchasing/order/:order_id/completeness',
      'GET /api/purchasing/:order_id',
      'POST /api/purchasing/:order_id/confirm',
      'POST /api/purchasing/:id/receive',
      'DELETE /api/purchasing/po/:po_id',
      'GET /api/purchasing/open-lines',
      'GET /api/purchasing/po/:po_id',
      'POST /api/purchasing/po/prepare',
      'POST /api/purchasing/po/:po_id/detach',
      'POST /api/purchasing/po/:po_id/discard',
      'POST /api/purchasing/lines/:id/cancel',
      'POST /api/purchasing/po/:po_id/submit',
      'POST /api/purchasing/po/:po_id/confirm',
      'POST /api/purchasing/lines',
      'POST /api/purchasing/lines/:id/settle',
    ],
    internalApi: [
      { fn: 'triggerPurchasing', file: 'services/purchasing-trigger-service.js' },
      { fn: 'resolveCanonicalSupplierMoney', file: 'services/purchasing-canonical-money.js' },
      { fn: 'evaluateSupplierFulfillmentReadiness', file: 'services/suppliers/supplier-fulfillment-readiness.js' },
      { fn: 'normalizeCapability', file: 'services/suppliers/shipping-capability-contract.js' },
      { fn: 'adaptShippingRate', file: 'services/suppliers/allegro-shipping-capability-adapter.js' },
      { fn: 'prepareCanonicalUnitPurchase', file: 'services/suppliers/canonical-unit-purchasing-gate.js' },
      { fn: 'compareLegacyCanonicalUnit', file: 'services/suppliers/canonical-unit-cutover-comparison.js' },
      { fn: 'reconcile', file: 'services/suppliers/allegro-purchase-reconciliation.js' },
      { fn: 'repairOrderedWithoutPurchaseOrders', file: 'services/repair-ordered-without-purchase-orders.js' },
      { fn: 'syncPurchaseOrdersOnOrderCancel', file: 'services/purchasing-cancel-service.js' },
      { fn: 'submitPurchaseOrder', file: 'services/purchasing-engagement-service.js' },
      { fn: 'confirmGroupedPurchaseOrder', file: 'services/purchasing-engagement-service.js' },
      { fn: 'settleLine', file: 'services/purchasing-engagement-service.js' },
      { fn: 'createManualLine', file: 'services/purchasing-engagement-service.js' },
    ],
    consumes: [
      'supplier-connectivity (autorité provider, Supplier Order Identity opaque et contrats adapter fail-closed)',
      'external-provider-contracts (contrat transverse de preuve provider : Conversation + KNOWN/DERIVED/UNKNOWN + P0..P4 consommé par les proofs Purchasing)',
      'sourcing (resolveCanonicalUnitForProductSku — frontière canonique exacte, sans lecture directe des tables Resolution)',
      'catalog (contrat V2 sellable_units + Supplier Order Identity fournie par les connecteurs, client Allegro Sandbox borné)',
      'infrastructure (dépendance technique transversale observée : DB, logger, helpers ou bootstrap possédés par infrastructure)',
      'orders (lecture : order_items, orders — le besoin d\'achat et l\'intention d\'annulation naissent d\'une commande client)',
      'auth (garde admin)',
      'notifications (notification fournisseur WhatsApp, via services/notification-service.js)',
      'logistics (declenche scan preparation + notification client apres reception hub complete — services/scan-operations.js triggerScan3, O7.2 Cycle C)',
    ],
  },

  debt: {
    knownGaps: [
      { gap: 'PR 2 de MISSION_PURCHASE_LINES : v_hub_transit et v_sourcing_pipeline (agrégats par PO, aucun consommateur dans le code, vérifié par recherche exhaustive) ne sont pas redéfinis via v_purchase_line_progress ; purchasing-cancel-service.js (annulation de commande) reste lu sur purchase_orders (hub-physical-identity.js lit la ligne d\'achat depuis la PR 3) ; receive-purchase-order.js (service de réception non branché) est inchangé.',
        risk: 'sans effet tant qu\'aucune PO regroupée n\'existe (drapeau KOMERCE_GROUPED_PURCHASING éteint). À traiter avant l\'activation : v_hub_transit / v_sourcing_pipeline à migrer ou retirer. purchasing-cancel-service.js gère désormais les lignes ouvertes et les PO regroupées (PR 4).',
      },
      { gap: 'PR 5 : une seule supplier_order_id par PO regroupée en V1 (le découpage d\'une commande AliExpress en plusieurs références vendeur n\'a pas de colonne dédiée) ; la ventilation par marché est une projection en lecture seule (quantités et montants confirmés par marché dans les réponses de confirm et settle), aucune refacturation ni table de règlement par marché n\'est écrite.',
        risk: 'sans effet drapeau éteint ; le règlement/coût par marché reste à construire à partir de v_purchase_line_market (marché de chaque ligne) et des montants confirmés des lignes.' },
      { gap: 'PR 7 : l\'expédition partielle d\'une commande (certains items reçus, d\'autres soldés sans reliquat) reste hors périmètre : une commande dont un item est sous-couvert reste en ordered jusqu\'au ré-achat du reliquat ou une décision humaine ; la réception Hub physique (identité d\'unité) n\'est exercée par l\'E2E qu\'au travers de ses écritures canoniques, couverte par les tests hub-physical-*.',
        risk: 'sans effet drapeau éteint ; surveillé par les signaux ordered_without_purchase_order (item non couvert) et purchase_order_receipt_stuck.' },
      { gap: 'purchase_lines est en écriture double avec purchase_orders (1 PO = 1 ligne) : aucune lecture ne dépend encore de la ligne (PR 2–8 de MISSION_PURCHASE_LINES). Écart assumé à la mission : FK order_item_id en ON DELETE CASCADE (et non RESTRICT) car ~20 scripts/tests e2e suppriment commandes et PO ; la suppression directe d\'une ligne reste bloquée par trigger (pg_trigger_depth).',
        risk: 'la garde I1 peut refuser une seconde PO pour un même order_item avec un autre mapping fournisseur ; l\'insertion est annulée au savepoint de l\'item et remonte en alerte purchasing_po_creation_failed. Contrôle de parité : npm run purchase-lines:parity.',
      },
      { gap: 'services/purchasing-admin-service.js écrit purchase_orders, product_suppliers, suppliers ' +
             'et orders, et est consommé par routes/purchasing.js — mais son header porte encore ' +
             '@domain dashboard (rattaché historiquement au manifest dashboard.feature.js). Son service ' +
             'réel est un service d\'achat (purchasing), pas une projection dashboard.',
        risk: 'multi-writer réel non résolu sur purchase_orders/suppliers/product_suppliers entre ' +
              'purchasing (ce manifest) et dashboard (via purchasing-admin-service.js) — documenté en ' +
              'ONTOLOGY_GAP plutôt que déplacé sans audit de flux.',
      },
    ],
  },

  authority: 'backend-core — tout changement du flux d\'engagement fournisseur (Procurement Route, readiness dynamique, déclenchement, confirmation, réception, annulation) doit rester derrière les services propriétaires purchasing ; supplier-connectivity possède l\'identité provider, la Supplier Order Identity et le contrat générique d\'adapter',

  invariants: [
    { statement: 'les lecteurs d\'achat (signaux, GET /api/purchasing, complétude de réception, scans Hub, stock-sync) lisent l\'engagé et le reçu par ligne via v_purchase_line_progress, jamais purchase_orders.qty/received_qty ; la vue redonne exactement l\'ancien calcul pour les PO historiques (avec ligne, sans ligne avant 225, annulées) et is_order_complete la consomme ; un item déjà couvert par les lignes (autre fournisseur compris) ne se rachète pas',
      test: 'tests/integration/purchase-line-progress-postgres.test.js' },
    { statement: 'purchase_lines (PR 1, migration 263) : la quantité effective achetée d\'un order_item (0 si annulée, sinon COALESCE(settled, confirmed, quantity)) ne dépasse jamais order_items.quantity — garde base I1 sous verrou FOR UPDATE sur order_items ; une ligne confirmée/réglée/annulée est figée (one-shot) et ne se supprime pas directement',
      test: 'tests/integration/purchase-lines-postgres.test.js' },
    { statement: 'forme regroupée (PR 4, migration 266, KOMERCE_GROUPED_PURCHASING éteint par défaut) : une PO est soit historique (order_id, qty, supplier_sku renseignés) soit regroupée (détail de ligne NULL, chk_purchase_orders_header_shape) ; une PO regroupée ne reçoit que des lignes à identité exacte, même fournisseur, même hub, même devise (garde base I4) ; rattachement, détachement, abandon et annulation de ligne se font en brouillon seulement ; une PO regroupée répond 409 PURCHASE_ORDER_GROUPED_USE_PO_ROUTES aux routes historiques ; le marché reste une propriété de chaque ligne (order_item → order → market_id, vue v_purchase_line_market) : une PO regroupée peut mêler KM/CM/CG, la clé de regroupement est fournisseur + hub (jamais le marché), le marché est visible dans open-lines, la préparation et la lecture de PO, market_id n\'est qu\'un filtre opérateur et Purchasing ne réassigne jamais un marché ; l\'annulation d\'une commande annule ses lignes ouvertes et en brouillon et n\'annule JAMAIS une ligne d\'une PO regroupée déjà soumise (alerte avec purchase_line_ids)',
      test: 'tests/integration/purchase-lines-grouped-postgres.test.js' },
    { statement: 'engagement d\'une PO regroupée (PR 5, KOMERCE_GROUPED_PURCHASING éteint par défaut) : submit ne passe une PO draft en notified que si chaque groupe supplier_unit_ref est prêt (préparation distante par groupe, quantité sommée) et que l\'adaptateur accepte les items (Allegro : une seule ligne, ALLEGRO_MULTI_ITEM_UNSUPPORTED) — sinon la PO reste draft avec les verdicts ; confirm exige exactement les lignes non annulées de la PO, écrit d\'abord la confirmation de chaque ligne puis le reliquat en ligne ouverte (parent_line_id, même instantané, I1 vérifie), passe la PO en confirmed (cancelled si tout est à 0) et ne confirme rien si la réconciliation fournisseur est rejetée ; settle (écart à la réception) solde une ligne confirmée à une quantité ≤ reçu du Hub et < effectif, puis crée le reliquat si reopen_remainder, et passe la PO en hub_received quand toutes ses lignes non annulées sont soldées ; POST /lines ne crée qu\'une ligne ouverte à identité exacte du même provider, I1 refuse tout sur-engagement ; chaque ligne garde son marché et les réponses l\'exposent par marché en lecture seule ; place_order_invoked reste false',
      test: 'tests/integration/purchase-lines-engagement-postgres.test.js' },
    { statement: 'complétude d\'achat (PR 7) : après le COMMIT d\'une réception Hub, une commande ordered ne passe en preparation (machine d\'états, source system, puis SCAN 3) que si chaque item non LOCAL_STOCK a une somme d\'effectifs de lignes non annulées ≥ sa quantité ET toutes ces lignes reçues ; une ligne soldée sans reliquat rouvert laisse l\'item sous-couvert et la commande bloquée (fail-closed, signal ordered_without_purchase_order) ; une PO regroupée dont toutes les lignes non annulées sont reçues passe en hub_received ; la réception Hub reste acquise si la complétude échoue (alerte, jamais d\'exception) ; second appel idempotent ; le chemin historique processReceive est inchangé',
      test: 'tests/e2e-api/purchasing.grouped-flow.e2e.test.js' },
    { statement: 'un besoin d\'achat déjà couvert par un bon de commande existant ne recrée jamais de doublon (idempotence applicative anti-replay, I-SWEEP-3B)',
      test: 'tests/e2e-api/purchasing.no-duplicate-po.e2e.test.js' },
    { statement: 'une ligne LOCAL_STOCK ne crée jamais de Purchase Order fournisseur ; seules les lignes IMPORT appartiennent au procurement fournisseur',
      test: 'tests/unit/purchasing-trigger-service.test.js' },
    { statement: 'si order_items.sku_id est renseigné, la Purchase Order doit conserver exactement ce product_sku_id, son supplier_unit_ref et sa Supplier Order Identity ; product_suppliers ne peut pas substituer un supplier_sku générique',
      test: 'tests/integration/purchasing-exact-sku-po.test.js' },
    { statement: 'pour une ligne SKU/SOI exacte, le prix et la devise du fournisseur viennent de la Canonical Unit et sont snapshotés nativement sur la PO ; un montant PLN/USD/CNY ne doit jamais être rebaptisé AED',
      test: 'tests/unit/purchasing-canonical-money.test.js' },
    { statement: 'une capacité de livraison provider ne franchit la frontière Purchasing que sous forme ShippingCapability canonique ; les champs natifs restent dans l\'adapter et tout fait décisionnel inconnu bloque au lieu d\'être inventé',
      test: 'tests/unit/allegro-shipping-capability-adapter.test.js' },
    { statement: 'CJ encapsule son contrat natif dans un adapter dédié : readiness exacte, buildOrderPayload et placeOrder idempotent avec recovery du code duplicate 1603003 ; cet adapter reste hors registry runtime tant que destination/logistique et cutover provider ne sont pas explicitement ouverts',
      test: 'tests/unit/cj-fulfillment-adapter.test.js' },
    { statement: 'Fulfillment Ready est un verdict dynamique SKU × quantité × Procurement Route ; identité résolue seule ne suffit pas et aucun preflight ne peut appeler placeOrder ni un paiement',
      test: 'tests/unit/supplier-fulfillment-readiness.test.js' },
    { statement: 'Allegro Sandbox peut être fulfillment-ready en exécution manuelle après identité + stock + prix live, tout en restant auto_order_ready=false et sans jamais invoquer de buyer placeOrder API',
      test: 'tests/unit/allegro-fulfillment-adapter.test.js' },
    { statement: 'une preuve d\'achat manuel Allegro ne confirme la PO que si une commande vendeur READY_FOR_PROCESSING correspond exactement à offer id/SOI, quantité et monnaie native ; la discovery est bornée dans le temps, zéro ou plusieurs matchs bloquent, un rejeu identique est idempotent et un rebind différent est refusé',
      test: 'tests/unit/allegro-sandbox-purchase-proof.test.js' },
    { statement: 'la destination fournisseur est dérivée d\'une Procurement Route explicite ; le moteur actuel n\'ouvre que PROCUREMENT_HUB et refuse une destination Market/client brute ainsi que tout mode direct fournisseur-client implicite',
      test: 'tests/unit/supplier-fulfillment-readiness.test.js' },
    { statement: 'pour AliExpress freight.calculate, l\'identité SKU reste résolue en amont mais le fret utilise uniquement le DTO complexe produit × quantité × destination hub encapsulé sous param_aeop_freight_calculate_for_buyer_d_t_o ; aucun sku_id n\'est inventé',
      test: 'tests/unit/aliexpress-purchase-preflight.test.js' },
    'purchasing peut consommer et lire la commande cliente, mais ne possède jamais son cycle de vie — toute mutation de orders.status continue de passer exclusivement par order-status-machine.js (feature orders)',
    'une réception ne peut être appliquée qu\'à un bon de commande existant et cohérent',
    'aucun consommateur cross-feature ne modifie purchase_orders directement : la synchronisation d\'annulation passe par purchasing-cancel-service.js',
    "tout message WhatsApp fournisseur part d un purchase_order déjà persisté ; un rejeu de notification ne recrée jamais le bon ni ne confirme son statut",
    'un préflight fournisseur ne peut jamais créer de commande fournisseur ni déclencher un paiement ; toute mutation externe exige un gate explicite séparé',
  ],

  classification: {
    kind:     'business-feature',
    decision: 'feature-autonome',
    signals: {
      ownsTables:          true,
      ownsLifecycle:       true,
      activeService:       true,
      multiConsumer:       false,
      ownsMigrations:      true,
      externalSideEffect:  'outbound-message',
      surface:             'api',
    },
    rationale: [
      'possède sa propre table (purchase_orders) avec un cycle de statut et un invariant d\'idempotence anti-replay propres',
      'scindé de orders : purchasing transforme un besoin d\'approvisionnement en engagement fournisseur sans jamais posséder le cycle de vie de la commande cliente',
    ],
  },

};
